/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import myassociation.controller.AssociationController;
import myassociation.model.Association;

/**
 *
 * @author Cláudio Felgueiras
 */
public class AssociationSettings extends javax.swing.JFrame {

    private static final long serialVersionUID = -7529338988103187213L;

    private AssociationController associationController;
    private Association associacao;
    private Point initialClick;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};

    /**
     * Creates new form Association
     */
    public AssociationSettings() {
        initComponents();
        associationController = new AssociationController();
        associacao = associationController.obterAssociacao();
        this.setIconImage(associationController.applicationIcon());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplMainSettings = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jtabbedAssocSettings = new javax.swing.JTabbedPane();
        jplGeneralSettings = new javax.swing.JPanel();
        btnGeneralSave = new javax.swing.JButton();
        jplSettingsLogo = new javax.swing.JPanel();
        lblApplicationLogo = new javax.swing.JLabel();
        btnApplicationLogo = new javax.swing.JButton();
        lblAssocName2 = new javax.swing.JLabel();
        jplSettingsColor = new javax.swing.JPanel();
        jccGeneral = new javax.swing.JColorChooser();
        lblGeneralColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 98, 206));
        setName("frmAssociationSettings"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplMainSettings.setBackground(new java.awt.Color(246, 246, 246));
        jplMainSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        jplMainSettings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jplMainSettingsMouseDragged(evt);
            }
        });
        jplMainSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplMainSettings.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 32));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplMainSettings.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 32, 32));

        jtabbedAssocSettings.setBackground(new java.awt.Color(255, 255, 255));
        jtabbedAssocSettings.setForeground(new java.awt.Color(0, 98, 206));
        jtabbedAssocSettings.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jtabbedAssocSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtabbedAssocSettings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jplGeneralSettings.setBackground(new java.awt.Color(246, 246, 246));
        jplGeneralSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplGeneralSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGeneralSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGeneralSave.setForeground(new java.awt.Color(0, 98, 206));
        btnGeneralSave.setText("Guardar");
        btnGeneralSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralSaveActionPerformed(evt);
            }
        });
        jplGeneralSettings.add(btnGeneralSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 93, 40));

        jplSettingsLogo.setBackground(new java.awt.Color(246, 246, 246));
        jplSettingsLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApplicationLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApplicationLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplSettingsLogo.add(lblApplicationLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 5, 130, 110));

        btnApplicationLogo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnApplicationLogo.setForeground(new java.awt.Color(0, 98, 206));
        btnApplicationLogo.setLabel("Logótipo");
        btnApplicationLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplicationLogoActionPerformed(evt);
            }
        });
        jplSettingsLogo.add(btnApplicationLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 130, 30));

        lblAssocName2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAssocName2.setForeground(new java.awt.Color(0, 98, 206));
        lblAssocName2.setText("Logótipo da aplicação:");
        jplSettingsLogo.add(lblAssocName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 26));

        jplGeneralSettings.add(jplSettingsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 160));

        jplSettingsColor.setBackground(new java.awt.Color(246, 246, 246));
        jplSettingsColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jccGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplSettingsColor.add(jccGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 5, 450, 240));

        lblGeneralColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGeneralColor.setForeground(new java.awt.Color(0, 98, 206));
        lblGeneralColor.setText("Côr dos menus:");
        jplSettingsColor.add(lblGeneralColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jplGeneralSettings.add(jplSettingsColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 700, 250));

        jtabbedAssocSettings.addTab("Geral", jplGeneralSettings);

        jplMainSettings.add(jtabbedAssocSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, 500));

        getContentPane().add(jplMainSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Definições da Associação",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(AssociationSettings.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void jplMainSettingsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplMainSettingsMouseDragged
        int thisX = this.getLocation().x;
        int thisY = this.getLocation().y;

        // Determine how much the mouse moved since the initial click
        int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
        int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        this.setLocation(X, Y);
    }//GEN-LAST:event_jplMainSettingsMouseDragged

    private void btnGeneralSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGeneralSaveActionPerformed

    private void btnApplicationLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplicationLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplicationLogoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplicationLogo;
    private javax.swing.JButton btnGeneralSave;
    private javax.swing.JColorChooser jccGeneral;
    private javax.swing.JPanel jplGeneralSettings;
    private javax.swing.JPanel jplMainSettings;
    private javax.swing.JPanel jplSettingsColor;
    private javax.swing.JPanel jplSettingsLogo;
    private javax.swing.JTabbedPane jtabbedAssocSettings;
    private javax.swing.JLabel lblApplicationLogo;
    private javax.swing.JLabel lblAssocName2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblGeneralColor;
    private javax.swing.JLabel lblMinimize;
    // End of variables declaration//GEN-END:variables
}
