/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myassociation.controller.AssociationController;
import myassociation.controller.MemberController;

/**
 *
 * @author Cláudio Felgueiras
 */
public class Category extends javax.swing.JFrame {

    private static final long serialVersionUID = 1950282651443806663L;

    private AssociationController associacaoController;
    private MemberController sociocontroller;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};

    /**
     * Creates new form CriarUtilizador
     */
    public Category() {
        initComponents();
        this.setLocationRelativeTo(null);
        associacaoController = new AssociationController();
        sociocontroller = new MemberController();
        jListaCategorias.setListData(sociocontroller.listaCategoriasSocios());
        this.setIconImage(associacaoController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.getRootPane().setDefaultButton(btnCategoriaCriar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplCategoriaCriar = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblTituloCategoria = new javax.swing.JLabel();
        jplCriarCategoria = new javax.swing.JPanel();
        btnCategoriaCriar = new javax.swing.JButton();
        txtCategoriaNome = new javax.swing.JTextField();
        lblCategoriaNome = new javax.swing.JLabel();
        jplListaCategorias = new javax.swing.JPanel();
        jspListaCategorias = new javax.swing.JScrollPane();
        jListaCategorias = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmCreateUser"); // NOI18N
        setUndecorated(true);

        jplCategoriaCriar.setBackground(new java.awt.Color(246, 246, 246));
        jplCategoriaCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplCategoriaCriar.setFocusable(false);
        jplCategoriaCriar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplCategoriaCriar.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 32, 32));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplCategoriaCriar.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 32, 32));

        lblTituloCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTituloCategoria.setForeground(new java.awt.Color(0, 98, 206));
        lblTituloCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCategoria.setText("CATEGORIAS");
        jplCategoriaCriar.add(lblTituloCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 0, 240, 30));

        jplCriarCategoria.setBackground(new java.awt.Color(246, 246, 246));

        btnCategoriaCriar.setBackground(new java.awt.Color(255, 255, 255));
        btnCategoriaCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCategoriaCriar.setForeground(new java.awt.Color(0, 98, 206));
        btnCategoriaCriar.setText("Criar");
        btnCategoriaCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaCriarActionPerformed(evt);
            }
        });

        lblCategoriaNome.setBackground(new java.awt.Color(204, 204, 204));
        lblCategoriaNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCategoriaNome.setForeground(new java.awt.Color(0, 98, 206));
        lblCategoriaNome.setText("Nome:");

        javax.swing.GroupLayout jplCriarCategoriaLayout = new javax.swing.GroupLayout(jplCriarCategoria);
        jplCriarCategoria.setLayout(jplCriarCategoriaLayout);
        jplCriarCategoriaLayout.setHorizontalGroup(
            jplCriarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCriarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jplCriarCategoriaLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnCategoriaCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplCriarCategoriaLayout.setVerticalGroup(
            jplCriarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplCriarCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jplCriarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCategoriaCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jplCategoriaCriar.add(jplCriarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 350, 100));

        jListaCategorias.setForeground(new java.awt.Color(0, 98, 206));
        jspListaCategorias.setViewportView(jListaCategorias);

        javax.swing.GroupLayout jplListaCategoriasLayout = new javax.swing.GroupLayout(jplListaCategorias);
        jplListaCategorias.setLayout(jplListaCategoriasLayout);
        jplListaCategoriasLayout.setHorizontalGroup(
            jplListaCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspListaCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jplListaCategoriasLayout.setVerticalGroup(
            jplListaCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspListaCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        jplCategoriaCriar.add(jplListaCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 350, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplCategoriaCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplCategoriaCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriaCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaCriarActionPerformed
        if (txtCategoriaNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O nome da categoria não pode ser vazio. \nInsira um nome de categoria.", "Criar Categoria", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean categoriacriada = sociocontroller.criarCategoria(txtCategoriaNome.getText());
            if (categoriacriada) {
                JOptionPane.showMessageDialog(null, "Categoria criado com sucesso.", "Categoria", JOptionPane.INFORMATION_MESSAGE);
                txtCategoriaNome.setText("");
                jListaCategorias.setListData(sociocontroller.listaCategoriasSocios());
            } else {
                JOptionPane.showMessageDialog(null, "Categoria já existe.\n Insira outro nome.", "Categoria", JOptionPane.ERROR_MESSAGE);
                txtCategoriaNome.setText("");
            }
        }
    }//GEN-LAST:event_btnCategoriaCriarActionPerformed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Criar categoria",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoriaCriar;
    private javax.swing.JList<String> jListaCategorias;
    private javax.swing.JPanel jplCategoriaCriar;
    private javax.swing.JPanel jplCriarCategoria;
    private javax.swing.JPanel jplListaCategorias;
    private javax.swing.JScrollPane jspListaCategorias;
    private javax.swing.JLabel lblCategoriaNome;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTituloCategoria;
    private javax.swing.JTextField txtCategoriaNome;
    // End of variables declaration//GEN-END:variables
}
