/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myassociation.controller.AssociationController;
import myassociation.controller.QuotaController;

/**
 *
 * @author Francisco Pereira
 */
public class CreateQuota extends javax.swing.JFrame {

    private static final long serialVersionUID = 7969534140008029512L;
    boolean criarQuota, verificado;;
    private AssociationController associacaoController = new AssociationController();
    private QuotaController quotaController = new QuotaController();
    private ImageIcon icon;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};

    /**
     * Creates new form CriarQuota
     */
    public CreateQuota() {
        initComponents();
        jLCategorias.setModel(new DefaultComboBoxModel<>(quotaController.listaCategoriasSocios()));
        this.setLocationRelativeTo(null);
        this.setIconImage(associacaoController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        jLCategorias.setSelectionModel(new DefaultListSelectionModel() {
        @Override
            public void setSelectionInterval(int index0, int index1) {
                if(super.isSelectedIndex(index0))
                {
                    super.removeSelectionInterval(index0, index1);
                }
                else
                {
                    super.addSelectionInterval(index0, index1);
                }
             }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplUtilCriar = new javax.swing.JPanel();
        lblUtilNome = new javax.swing.JLabel();
        lblUtilSenha = new javax.swing.JLabel();
        txtQuotaAno = new javax.swing.JTextField();
        btnUtilCriar = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblUtilGrupo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLCategorias = new javax.swing.JList<>();
        txtQuotaValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmCreateUser"); // NOI18N
        setUndecorated(true);

        jplUtilCriar.setBackground(new java.awt.Color(246, 246, 246));
        jplUtilCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplUtilCriar.setFocusable(false);
        jplUtilCriar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUtilNome.setBackground(new java.awt.Color(204, 204, 204));
        lblUtilNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilNome.setForeground(new java.awt.Color(0, 98, 206));
        lblUtilNome.setText("Valor:");
        jplUtilCriar.add(lblUtilNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, 54, 24));

        lblUtilSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilSenha.setForeground(new java.awt.Color(0, 98, 206));
        lblUtilSenha.setText("Ano:");
        jplUtilCriar.add(lblUtilSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 54, 24));
        jplUtilCriar.add(txtQuotaAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, 24));

        btnUtilCriar.setBackground(new java.awt.Color(255, 255, 255));
        btnUtilCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUtilCriar.setForeground(new java.awt.Color(0, 98, 206));
        btnUtilCriar.setText("Criar");
        btnUtilCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilCriarActionPerformed(evt);
            }
        });
        jplUtilCriar.add(btnUtilCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 93, 40));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 32, 32));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 32, 32));

        lblUtilGrupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilGrupo.setForeground(new java.awt.Color(0, 98, 206));
        lblUtilGrupo.setText("Grupo:");
        jplUtilCriar.add(lblUtilGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 54, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 98, 206));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEFINIR QUOTA");
        jplUtilCriar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 290, 30));
        jLabel1.getAccessibleContext().setAccessibleName("DEFINIR QUOTA");

        jLCategorias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLCategorias);

        jplUtilCriar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 280, 50));

        txtQuotaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuotaValorActionPerformed(evt);
            }
        });
        jplUtilCriar.add(txtQuotaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUtilCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilCriarActionPerformed
        /*Valida se campos estão vazios*/
        if (txtQuotaAno.getText().isEmpty() || txtQuotaValor.getText().isEmpty() || jLCategorias.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os dados referentes à quota não podem ser vazios . "
                    + "\nInsira um Valor, um Ano Válido e selecione pelo menos uma categoria.", "Definir Quota", JOptionPane.ERROR_MESSAGE); 
            
        } 
        /*Valida se campos estão preenchidos corretamente*/
        /*Desta forma só permite preenchimento de anos que comecem pelo número 2*/  /*|| (!Pattern.matches("^\\d*\\.\\d+|\\d+\\.\\d*$  ", txtQuotaValor.getText()) == true)*/
        else if ((!Pattern.matches("[2][0-9][0-9][0-9]", txtQuotaAno.getText()) == true) )
        {
            JOptionPane.showMessageDialog(null, "Os dados referentes à quota tem de ser obrigat+oriamente do tipo numérico . "
                    + "\nInsira um Valor e/ou um Ano Válido.", "Definir Quota", JOptionPane.ERROR_MESSAGE);        
        }
       else { 
           
            List myList = new ArrayList();
            myList = jLCategorias.getSelectedValuesList();
            for(Object item : myList){
		int categoria = quotaController.getCategoriaIdPorNome(item.toString());    
                verificado = quotaController.verificaQuotaPorAnoCategoria(Integer.parseInt(txtQuotaAno.getText()), categoria);
                if (verificado==false){
                    criarQuota = quotaController.criarQuota(Double.parseDouble(txtQuotaValor.getText()),Integer.parseInt(txtQuotaAno.getText()),categoria);
                    System.out.println(criarQuota);
                }
            }  
  
                if (criarQuota) {
                        JOptionPane.showMessageDialog(null, "Valor de Quota criada com sucesso.", "Quota",
                        JOptionPane.INFORMATION_MESSAGE); txtQuotaAno.setText(""); txtQuotaValor.setText("");             
                    } 
                
                else {
                    JOptionPane.showMessageDialog(null, "Já existe quotas criadas para o ano selecionado e para a categoria selecionada!\n Preencha novamente os dados.", "Quota",
                    JOptionPane.ERROR_MESSAGE); txtQuotaAno.setText(""); txtQuotaValor.setText(""); 
                 }
        } 
         

    }//GEN-LAST:event_btnUtilCriarActionPerformed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Definir Quota",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void txtQuotaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuotaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuotaValorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUtilCriar;
    private javax.swing.JList<String> jLCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplUtilCriar;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblUtilGrupo;
    private javax.swing.JLabel lblUtilNome;
    private javax.swing.JLabel lblUtilSenha;
    private javax.swing.JTextField txtQuotaAno;
    private javax.swing.JTextField txtQuotaValor;
    // End of variables declaration//GEN-END:variables
}
