/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import myassociation.controller.AssociationController;
import myassociation.controller.MemberController;

/**
 *
 * @author Cláudio Felgueiras
 */
public class CreateMember extends javax.swing.JFrame {

    private static final long serialVersionUID = 1531678817826707765L;

    private MemberController socioController = new MemberController();
    private AssociationController assocController = new AssociationController();
    private Point initialClick;
    private BufferedImage foto;
    private File ficheiro;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};
    private String username;

    /**
     * Creates new form CriarSocio
     *
     * @param username
     */
    public CreateMember(String username) {
        initComponents();
        this.setIconImage(assocController.applicationIcon());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.username = username;
        jcbSociosCategoria.setModel(new DefaultComboBoxModel<>(socioController.listaCategoriasSocios()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplCriarSocio = new javax.swing.JPanel();
        lblSociosNumero = new javax.swing.JLabel();
        lblSociosMorada = new javax.swing.JLabel();
        lblSociosNIF = new javax.swing.JLabel();
        lblSociosEmail = new javax.swing.JLabel();
        txtSociosNumero = new javax.swing.JTextField();
        txtSociosMorada = new javax.swing.JTextField();
        txtSociosNIF = new javax.swing.JTextField();
        txtSociosEmail = new javax.swing.JTextField();
        lblSociosNome = new javax.swing.JLabel();
        txtSociosNome = new javax.swing.JTextField();
        lblSociosFoto = new javax.swing.JLabel();
        btnSociosCriar = new javax.swing.JButton();
        btnSociosFoto = new javax.swing.JButton();
        lblSociosTelefone = new javax.swing.JLabel();
        txtSociosTelefone = new javax.swing.JTextField();
        lblSociosTelemovel = new javax.swing.JLabel();
        txtSociosTelemovel = new javax.swing.JTextField();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblCriarSocioTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbSociosCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 98, 206));
        setName("frmCreateMember"); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jplCriarSocio.setBackground(new java.awt.Color(246, 246, 246));
        jplCriarSocio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jplCriarSocio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jplCriarSocioMouseDragged(evt);
            }
        });
        jplCriarSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jplCriarSocioMousePressed(evt);
            }
        });
        jplCriarSocio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSociosNumero.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNumero.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNumero.setText("Número:");
        jplCriarSocio.add(lblSociosNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 62, 26));

        lblSociosMorada.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosMorada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosMorada.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosMorada.setText("Morada:");
        jplCriarSocio.add(lblSociosMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 66, 26));

        lblSociosNIF.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNIF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNIF.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNIF.setText("NIF:");
        jplCriarSocio.add(lblSociosNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 62, 26));

        lblSociosEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosEmail.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosEmail.setText("E-mail:");
        jplCriarSocio.add(lblSociosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 66, 26));
        jplCriarSocio.add(txtSociosNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 208, 26));
        jplCriarSocio.add(txtSociosMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 440, 26));
        jplCriarSocio.add(txtSociosNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 210, 26));
        jplCriarSocio.add(txtSociosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 440, 26));

        lblSociosNome.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNome.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNome.setText("Nome:");
        jplCriarSocio.add(lblSociosNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 62, 26));
        jplCriarSocio.add(txtSociosNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 300, 26));

        lblSociosFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSociosFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplCriarSocio.add(lblSociosFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 118, 113));

        btnSociosCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSociosCriar.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosCriar.setText("Criar");
        btnSociosCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosCriarActionPerformed(evt);
            }
        });
        jplCriarSocio.add(btnSociosCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 93, 40));

        btnSociosFoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSociosFoto.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosFoto.setText("Fotografia");
        btnSociosFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosFotoActionPerformed(evt);
            }
        });
        jplCriarSocio.add(btnSociosFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 99, 30));

        lblSociosTelefone.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosTelefone.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTelefone.setText("Telefone:");
        jplCriarSocio.add(lblSociosTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 58, 22));
        jplCriarSocio.add(txtSociosTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 170, 26));

        lblSociosTelemovel.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosTelemovel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosTelemovel.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTelemovel.setText("Telemóvel:");
        jplCriarSocio.add(lblSociosTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 66, 26));
        jplCriarSocio.add(txtSociosTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 170, 30));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplCriarSocio.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 32, 32));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplCriarSocio.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 32, 32));

        lblCriarSocioTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCriarSocioTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblCriarSocioTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCriarSocioTitulo.setText("CRIAR SÓCIO");
        jplCriarSocio.add(lblCriarSocioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 430, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 98, 206));
        jLabel2.setText("Categoria:");
        jplCriarSocio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 66, 26));

        jplCriarSocio.add(jcbSociosCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jplCriarSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jplCriarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSociosCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosCriarActionPerformed
        try {
            boolean ativo = true;
            boolean apagado = false;
            if (txtSociosNumero.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O número de sócio não pode ser vazio. \nInsira um número válido.", "Criar sócio", JOptionPane.ERROR_MESSAGE);
            } else if (!Pattern.matches("[0-9]+", txtSociosNumero.getText()) == true) {
                JOptionPane.showMessageDialog(null, "O campo número de sócio apenas pode conter números. \nInsira um número válido.", "Criar sócio", JOptionPane.ERROR_MESSAGE);
                txtSociosNumero.setText("");
            } else if (jcbSociosCategoria.getItemCount() == 0) {
                JOptionPane.showMessageDialog(null, "Não existem categorias de sócio criadas. \nCrie novas categorias no menu anterior.", "Criar categoria", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean sociocriado = socioController.criarSocio(txtSociosNumero.getText(),
                        txtSociosNome.getText(), txtSociosMorada.getText(), txtSociosNIF.getText(),
                        txtSociosEmail.getText(), txtSociosTelefone.getText(), txtSociosTelemovel.getText(),
                        convertImagetoByte(foto), ativo, apagado,
                        (String) jcbSociosCategoria.getSelectedItem(), username);
                if (!sociocriado) {
                    JOptionPane.showMessageDialog(null, "Erro ao criar sócio.\n Verifique os dados.", "Criar sócio", JOptionPane.ERROR_MESSAGE);
                    txtSociosNumero.setText("");
                    txtSociosNome.setText("");
                    txtSociosMorada.setText("");
                    txtSociosNIF.setText("");
                    txtSociosEmail.setText("");
                    txtSociosTelefone.setText("");
                    txtSociosTelemovel.setText("");
                    lblSociosFoto.setIcon(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Socio criado com sucesso.", "Criar sócio", JOptionPane.INFORMATION_MESSAGE);
                    txtSociosNumero.setText("");
                    txtSociosNome.setText("");
                    txtSociosMorada.setText("");
                    txtSociosNIF.setText("");
                    txtSociosEmail.setText("");
                    txtSociosTelefone.setText("");
                    txtSociosTelemovel.setText("");
                    lblSociosFoto.setIcon(null);
                }
            }
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSociosCriarActionPerformed

    private void btnSociosFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosFotoActionPerformed

        try {
            JFileChooser filechooser = new JFileChooser();
            filechooser.setDialogTitle("Escolha a fotografia");
            FileFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "bmp", "png", "tif");
            filechooser.setFileFilter(filter);
            filechooser.setAcceptAllFileFilterUsed(false);
            filechooser.showOpenDialog(this);
            ficheiro = filechooser.getSelectedFile();
            foto = ImageIO.read(ficheiro);
            Image fotodim = foto.getScaledInstance(lblSociosFoto.getWidth(), lblSociosFoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icone = new ImageIcon(fotodim);
            lblSociosFoto.setIcon(icone);
        } catch (IOException | IllegalArgumentException | NullPointerException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSociosFotoActionPerformed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Criar sócio",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void jplCriarSocioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplCriarSocioMouseDragged
        int thisX = this.getLocation().x;
        int thisY = this.getLocation().y;

        // Determine how much the mouse moved since the initial click
        int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
        int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        this.setLocation(X, Y);
    }//GEN-LAST:event_jplCriarSocioMouseDragged

    private void jplCriarSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplCriarSocioMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_jplCriarSocioMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (jcbSociosCategoria.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Não existem categorias de sócio criadas. \nCrie novas categorias no menu anterior.", "Criar categoria", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSociosCriar;
    private javax.swing.JButton btnSociosFoto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcbSociosCategoria;
    private javax.swing.JPanel jplCriarSocio;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCriarSocioTitulo;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSociosEmail;
    private javax.swing.JLabel lblSociosFoto;
    private javax.swing.JLabel lblSociosMorada;
    private javax.swing.JLabel lblSociosNIF;
    private javax.swing.JLabel lblSociosNome;
    private javax.swing.JLabel lblSociosNumero;
    private javax.swing.JLabel lblSociosTelefone;
    private javax.swing.JLabel lblSociosTelemovel;
    private javax.swing.JTextField txtSociosEmail;
    private javax.swing.JTextField txtSociosMorada;
    private javax.swing.JTextField txtSociosNIF;
    private javax.swing.JTextField txtSociosNome;
    private javax.swing.JTextField txtSociosNumero;
    private javax.swing.JTextField txtSociosTelefone;
    private javax.swing.JTextField txtSociosTelemovel;
    // End of variables declaration//GEN-END:variables

    private byte[] convertImagetoByte(BufferedImage foto) throws IOException {
        byte[] fotoinbytes;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        if (foto == null) {
            fotoinbytes = new byte[0];
        } else {
            try {
                foto = ImageIO.read(ficheiro);

                ImageIO.write(foto, "jpg", baos);
                baos.flush();
                baos.toByteArray();
            } catch (IOException ex) {
                Logger.getLogger(CreateMember.class.getName()).log(Level.SEVERE, null, ex);
            }
            fotoinbytes = baos.toByteArray();
        }
        return fotoinbytes;
    }
}
