/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myassociation.controller.AssociationController;
import myassociation.controller.SportController;
import myassociation.controller.UserController;

/**
 *
 * @author Cláudio Felgueiras
 */
public class CreateSport extends javax.swing.JFrame {

    private static final long serialVersionUID = 9159801668819494747L;

    private AssociationController associacaoController;
    private SportController modalidadeController;
    private UserController utilizadorController;
    String username;
    private ImageIcon icon;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};

    /**
     * Creates new form CriarUtilizador
     * @param username
     */
    public CreateSport(String username) {
        initComponents();
        modalidadeController = new SportController();
        associacaoController = new AssociationController();
        utilizadorController = new UserController();
        this.username = username;
        this.setLocationRelativeTo(null);
        this.setIconImage(associacaoController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplUtilCriar = new javax.swing.JPanel();
        lblModNome = new javax.swing.JLabel();
        lblModResponsavel = new javax.swing.JLabel();
        txtModResponsavel = new javax.swing.JTextField();
        btnModCriar = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblModCriar = new javax.swing.JLabel();
        txtModNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmCreateUser"); // NOI18N
        setUndecorated(true);

        jplUtilCriar.setBackground(new java.awt.Color(246, 246, 246));
        jplUtilCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplUtilCriar.setFocusable(false);
        jplUtilCriar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModNome.setBackground(new java.awt.Color(204, 204, 204));
        lblModNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModNome.setForeground(new java.awt.Color(0, 98, 206));
        lblModNome.setText("Nome:");
        jplUtilCriar.add(lblModNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 26));

        lblModResponsavel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModResponsavel.setForeground(new java.awt.Color(0, 98, 206));
        lblModResponsavel.setText("Responsável:");
        jplUtilCriar.add(lblModResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 26));
        jplUtilCriar.add(txtModResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, 26));

        btnModCriar.setBackground(new java.awt.Color(255, 255, 255));
        btnModCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModCriar.setForeground(new java.awt.Color(0, 98, 206));
        btnModCriar.setText("Criar");
        btnModCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCriarActionPerformed(evt);
            }
        });
        jplUtilCriar.add(btnModCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 93, 40));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 32, 32));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 32, 32));

        lblModCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModCriar.setForeground(new java.awt.Color(0, 98, 206));
        lblModCriar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModCriar.setText("CRIAR MODALIDADE");
        jplUtilCriar.add(lblModCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 290, 30));
        jplUtilCriar.add(txtModNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 290, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCriarActionPerformed
        if (txtModNome.getText().isEmpty() || txtModResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os dados da modalidade não podem ser vazios. \nInsira um nome e um responsável.", "Criar Modalidade", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean modcriada = modalidadeController.criarModalidade(txtModNome.getText(), txtModResponsavel.getText(), true, username);
            if (modcriada) {
                JOptionPane.showMessageDialog(null, "Modalidade criada com sucesso.", "Modalidade", JOptionPane.INFORMATION_MESSAGE);
                txtModNome.setText("");
                txtModResponsavel.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Modalidade já existe.\n Insira outro nome de modalidade.", "Modalidade", JOptionPane.ERROR_MESSAGE);
                txtModNome.setText("");
                txtModResponsavel.setText("");
            }
        }
    }//GEN-LAST:event_btnModCriarActionPerformed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Criar Modalidade",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModCriar;
    private javax.swing.JPanel jplUtilCriar;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblModCriar;
    private javax.swing.JLabel lblModNome;
    private javax.swing.JLabel lblModResponsavel;
    private javax.swing.JTextField txtModNome;
    private javax.swing.JTextField txtModResponsavel;
    // End of variables declaration//GEN-END:variables
}
