/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myassociation.controller.AssociationController;
import myassociation.controller.SportController;
import myassociation.controller.UserController;
import myassociation.model.Sport;

/**
 *
 * @author Cláudio Felgueiras
 */
public class EditSport extends javax.swing.JFrame {

    private static final long serialVersionUID = 969704772561189841L;

    private AssociationController associacaoController;
    private SportController modalidadeController;
    private UserController utilizadorController;
    private Sport modalidade;
    private String username;
    private ImageIcon icon;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};

    /**
     * Creates new form CriarUtilizador
     *
     * @param modalidade
     * @param username
     */
    public EditSport(Sport modalidade, String username) {
        initComponents();
        modalidadeController = new SportController();
        associacaoController = new AssociationController();
        utilizadorController = new UserController();
        this.modalidade = modalidade;
        this.username = username;
        setDados();
        this.setLocationRelativeTo(null);
        this.setIconImage(associacaoController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplUtilCriar = new javax.swing.JPanel();
        lblModNome = new javax.swing.JLabel();
        lblModResponsavel = new javax.swing.JLabel();
        txtModResponsavel = new javax.swing.JTextField();
        btnModValidar = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblModEditar = new javax.swing.JLabel();
        txtModNome = new javax.swing.JTextField();
        btnModCancelar = new javax.swing.JButton();
        lblModEstado = new javax.swing.JLabel();
        checkModEstado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmCreateUser"); // NOI18N
        setUndecorated(true);

        jplUtilCriar.setBackground(new java.awt.Color(246, 246, 246));
        jplUtilCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplUtilCriar.setFocusable(false);
        jplUtilCriar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModNome.setBackground(new java.awt.Color(204, 204, 204));
        lblModNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModNome.setForeground(new java.awt.Color(0, 98, 206));
        lblModNome.setText("Nome:");
        jplUtilCriar.add(lblModNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 26));

        lblModResponsavel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModResponsavel.setForeground(new java.awt.Color(0, 98, 206));
        lblModResponsavel.setText("Responsável:");
        jplUtilCriar.add(lblModResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 26));
        jplUtilCriar.add(txtModResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, 26));

        btnModValidar.setBackground(new java.awt.Color(255, 255, 255));
        btnModValidar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModValidar.setForeground(new java.awt.Color(0, 98, 206));
        btnModValidar.setText("Validar");
        btnModValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModValidarActionPerformed(evt);
            }
        });
        jplUtilCriar.add(btnModValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 93, 40));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 32, 32));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 32, 32));

        lblModEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModEditar.setForeground(new java.awt.Color(0, 98, 206));
        lblModEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModEditar.setText("EDITAR MODALIDADE");
        jplUtilCriar.add(lblModEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 290, 30));
        jplUtilCriar.add(txtModNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 290, 26));

        btnModCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModCancelar.setForeground(new java.awt.Color(0, 98, 206));
        btnModCancelar.setText("Cancelar");
        btnModCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCancelarActionPerformed(evt);
            }
        });
        jplUtilCriar.add(btnModCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 93, 40));

        lblModEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModEstado.setForeground(new java.awt.Color(0, 98, 206));
        lblModEstado.setText("Ativo:");
        jplUtilCriar.add(lblModEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 66, 25));

        checkModEstado.setBackground(new java.awt.Color(255, 255, 255));
        jplUtilCriar.add(checkModEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModValidarActionPerformed
        boolean ativo = true;
        boolean modalidadeEditada = modalidadeController.editarModalidade(txtModNome.getText(), txtModResponsavel.getText(), ativo, username);
        if (!modalidadeEditada) {
            JOptionPane.showMessageDialog(null, "Modalidade já existe.\n Insira outros dados.", "Modalidade", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Modalidade editada com sucesso.", "Modalidade", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnModValidarActionPerformed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Criar sócio",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void btnModCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnModCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModCancelar;
    private javax.swing.JButton btnModValidar;
    private javax.swing.JCheckBox checkModEstado;
    private javax.swing.JPanel jplUtilCriar;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblModEditar;
    private javax.swing.JLabel lblModEstado;
    private javax.swing.JLabel lblModNome;
    private javax.swing.JLabel lblModResponsavel;
    private javax.swing.JTextField txtModNome;
    private javax.swing.JTextField txtModResponsavel;
    // End of variables declaration//GEN-END:variables

    private void setDados() {
        txtModNome.setText(modalidade.getNome());
        txtModResponsavel.setText(modalidade.getResponsavel());
        checkModEstado.setSelected(modalidade.getEstado());
    }
}
