/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import myassociation.controller.AssociationController;
import myassociation.controller.MemberController;
import myassociation.model.Member;

/**
 *
 * @author Cláudio Felgueiras
 */
public class EditMember extends javax.swing.JFrame {

    private static final long serialVersionUID = -7748229361707008924L;

    private MemberController socioController = new MemberController();
    private AssociationController assocController = new AssociationController();
    private Point initialClick;
    private BufferedImage foto;
    private File ficheiro;
    private Member member;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};
    private String username;

    /**
     * Creates new form CriarSocio
     *
     * @param member
     * @param username
     * @throws java.io.IOException
     */
    public EditMember(Member member, String username) throws IOException {
        initComponents();
        this.member = member;
        this.username = username;
        setDados();
        foto = createImageFromBytes(member.getFotografia());
        System.out.println(foto);
        jcbSociosCategoria.setModel(new DefaultComboBoxModel<>(socioController.listaCategoriasSocios()));
        jcbSociosAssociacao.setModel(new DefaultComboBoxModel<>(assocController.listaNomesAssociacoes()));
        this.setLocationRelativeTo(null);
        this.setIconImage(assocController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplEditarSocio = new javax.swing.JPanel();
        checkSociosEstado = new javax.swing.JCheckBox();
        lblSociosEstado = new javax.swing.JLabel();
        lblSociosEmail = new javax.swing.JLabel();
        txtSociosEmail = new javax.swing.JTextField();
        lblSociosMorada = new javax.swing.JLabel();
        txtSociosMorada = new javax.swing.JTextField();
        lblSociosFoto = new javax.swing.JLabel();
        btnSociosFoto = new javax.swing.JButton();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        txtSociosTelemovel = new javax.swing.JTextField();
        lblSociosTelemovel = new javax.swing.JLabel();
        lblSociosTelefone = new javax.swing.JLabel();
        txtSociosTelefone = new javax.swing.JTextField();
        txtSociosNome = new javax.swing.JTextField();
        lblSociosNome = new javax.swing.JLabel();
        txtSociosNIF = new javax.swing.JTextField();
        lblSociosNIF = new javax.swing.JLabel();
        lblSociosNumero = new javax.swing.JLabel();
        txtSociosNumero = new javax.swing.JTextField();
        btnSociosCancelar = new javax.swing.JButton();
        btnSociosEditar = new javax.swing.JButton();
        lblEditarSocioTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbSociosCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jcbSociosAssociacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmEditMember"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jplEditarSocio.setBackground(new java.awt.Color(246, 246, 246));
        jplEditarSocio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplEditarSocio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jplEditarSocioMouseDragged(evt);
            }
        });
        jplEditarSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jplEditarSocioMousePressed(evt);
            }
        });
        jplEditarSocio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkSociosEstado.setBackground(new java.awt.Color(255, 255, 255));
        jplEditarSocio.add(checkSociosEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        lblSociosEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosEstado.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosEstado.setText("Ativo:");
        jplEditarSocio.add(lblSociosEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 66, 25));

        lblSociosEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosEmail.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosEmail.setText("E-mail:");
        jplEditarSocio.add(lblSociosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 66, 26));
        jplEditarSocio.add(txtSociosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 440, 26));

        lblSociosMorada.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosMorada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosMorada.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosMorada.setText("Morada:");
        jplEditarSocio.add(lblSociosMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 66, 26));
        jplEditarSocio.add(txtSociosMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 440, 26));

        lblSociosFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSociosFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplEditarSocio.add(lblSociosFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 118, 113));

        btnSociosFoto.setBackground(new java.awt.Color(255, 255, 255));
        btnSociosFoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSociosFoto.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosFoto.setText("Fotografia");
        btnSociosFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosFotoActionPerformed(evt);
            }
        });
        jplEditarSocio.add(btnSociosFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 99, 30));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplEditarSocio.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 32, 32));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplEditarSocio.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 32, 32));
        jplEditarSocio.add(txtSociosTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 170, 25));

        lblSociosTelemovel.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosTelemovel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosTelemovel.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTelemovel.setText("Telemovel:");
        jplEditarSocio.add(lblSociosTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 66, 26));

        lblSociosTelefone.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosTelefone.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTelefone.setText("Telefone:");
        jplEditarSocio.add(lblSociosTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 58, 22));
        jplEditarSocio.add(txtSociosTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 170, 25));
        jplEditarSocio.add(txtSociosNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 300, 26));

        lblSociosNome.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNome.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNome.setText("Nome:");
        jplEditarSocio.add(lblSociosNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 62, 26));
        jplEditarSocio.add(txtSociosNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 210, 26));

        lblSociosNIF.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNIF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNIF.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNIF.setText("NIF:");
        jplEditarSocio.add(lblSociosNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 62, 26));

        lblSociosNumero.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNumero.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNumero.setText("Número:");
        jplEditarSocio.add(lblSociosNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 62, 26));

        txtSociosNumero.setEnabled(false);
        jplEditarSocio.add(txtSociosNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 208, 26));

        btnSociosCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSociosCancelar.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosCancelar.setText("Cancelar");
        btnSociosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosCancelarActionPerformed(evt);
            }
        });
        jplEditarSocio.add(btnSociosCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 93, 40));

        btnSociosEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSociosEditar.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosEditar.setText("Validar");
        btnSociosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosEditarActionPerformed(evt);
            }
        });
        jplEditarSocio.add(btnSociosEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 93, 40));

        lblEditarSocioTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditarSocioTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblEditarSocioTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditarSocioTitulo.setText("EDITAR SÓCIO");
        jplEditarSocio.add(lblEditarSocioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 430, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 98, 206));
        jLabel2.setText("Categoria:");
        jplEditarSocio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 66, 26));

        jplEditarSocio.add(jcbSociosCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, 26));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 98, 206));
        jLabel1.setText("Associação:");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 15));
        jplEditarSocio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 26));

        jplEditarSocio.add(jcbSociosAssociacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 210, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplEditarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplEditarSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSociosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosEditarActionPerformed
        try {
            boolean ativo = true;
            byte[] fotografia = convertImagetoByte(foto);
            System.out.println("Dentro do metodo: " + foto);
            boolean socioeditado = socioController.editarSocio(txtSociosNumero.getText(), txtSociosNome.getText(), txtSociosMorada.getText(), txtSociosNIF.getText(), txtSociosEmail.getText(), txtSociosTelefone.getText(), txtSociosTelemovel.getText(), fotografia, ativo, (String)jcbSociosCategoria.getSelectedItem(), (String)jcbSociosAssociacao.getSelectedItem(), username);
            System.out.println("");
            if (!socioeditado) {
                JOptionPane.showMessageDialog(null, "Socio já existe.\n Insira outros dados.", "Socios", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Socio editado com sucesso.", "Socios", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (IOException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnSociosEditarActionPerformed

    private void btnSociosFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosFotoActionPerformed
        try {
            JFileChooser filechooser = new JFileChooser();
            filechooser.setDialogTitle("Escolha a fotografia");
            FileFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "bmp", "png", "tif");
            filechooser.setFileFilter(filter);
            filechooser.setAcceptAllFileFilterUsed(false);
            filechooser.showOpenDialog(this);
            ficheiro = filechooser.getSelectedFile();
            foto = ImageIO.read(ficheiro);
            Image fotodim = foto.getScaledInstance(lblSociosFoto.getWidth(), lblSociosFoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icone = new ImageIcon(fotodim);
            lblSociosFoto.setIcon(icone);
        } catch (IOException | IllegalArgumentException | NullPointerException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSociosFotoActionPerformed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Criar sócio",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void btnSociosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSociosCancelarActionPerformed

    private void jplEditarSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEditarSocioMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_jplEditarSocioMousePressed

    private void jplEditarSocioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEditarSocioMouseDragged
        int thisX = this.getLocation().x;
        int thisY = this.getLocation().y;

        // Determine how much the mouse moved since the initial click
        int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
        int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        this.setLocation(X, Y);
    }//GEN-LAST:event_jplEditarSocioMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSociosCancelar;
    private javax.swing.JButton btnSociosEditar;
    private javax.swing.JButton btnSociosFoto;
    private javax.swing.JCheckBox checkSociosEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcbSociosAssociacao;
    private javax.swing.JComboBox<String> jcbSociosCategoria;
    private javax.swing.JPanel jplEditarSocio;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEditarSocioTitulo;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSociosEmail;
    private javax.swing.JLabel lblSociosEstado;
    private javax.swing.JLabel lblSociosFoto;
    private javax.swing.JLabel lblSociosMorada;
    private javax.swing.JLabel lblSociosNIF;
    private javax.swing.JLabel lblSociosNome;
    private javax.swing.JLabel lblSociosNumero;
    private javax.swing.JLabel lblSociosTelefone;
    private javax.swing.JLabel lblSociosTelemovel;
    private javax.swing.JTextField txtSociosEmail;
    private javax.swing.JTextField txtSociosMorada;
    private javax.swing.JTextField txtSociosNIF;
    private javax.swing.JTextField txtSociosNome;
    private javax.swing.JTextField txtSociosNumero;
    private javax.swing.JTextField txtSociosTelefone;
    private javax.swing.JTextField txtSociosTelemovel;
    // End of variables declaration//GEN-END:variables

    private byte[] convertImagetoByte(BufferedImage foto) throws IOException {
        byte[] fotoinbytes;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        if (foto == null) {
            fotoinbytes = new byte[0];
        } else if (ficheiro == null) {
            fotoinbytes = member.getFotografia();
        } else {
            try {
                foto = ImageIO.read(ficheiro);

                ImageIO.write(foto, "jpg", baos);
                baos.flush();
                baos.toByteArray();
            } catch (IOException ex) {
                Logger.getLogger(EditMember.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(EditMember.class.getName()).log(Level.SEVERE, null, ex);
            }
            fotoinbytes = baos.toByteArray();;
        }
        return fotoinbytes;
    }

    private Icon convertBytetoIcon(byte[] fotografia) {
        ImageIcon icone = null;
        try {
            byte[] byteArray = fotografia;
            BufferedImage theImage = ImageIO.read(new ByteArrayInputStream(byteArray));
            Image fotodim = theImage.getScaledInstance(lblSociosFoto.getWidth(), lblSociosFoto.getHeight(), Image.SCALE_SMOOTH);
            icone = new ImageIcon(fotodim);

        } catch (IOException ex) {
            System.out.println(ex);
        } catch (NullPointerException exep) {
            System.out.println(exep);
        }
        return icone;
    }

    private BufferedImage createImageFromBytes(byte[] fotografia) {
        ByteArrayInputStream bais = new ByteArrayInputStream(fotografia);
        try {
            return ImageIO.read(bais);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private void setDados() {
        txtSociosNumero.setText(member.getNumero());
        txtSociosNome.setText(member.getNome());
        txtSociosMorada.setText(member.getMorada());
        txtSociosNIF.setText(member.getNif());
        txtSociosEmail.setText(member.getEmail());
        txtSociosTelefone.setText(member.getTelefone());
        txtSociosTelemovel.setText(member.getTelemovel());
        lblSociosFoto.setIcon(convertBytetoIcon(member.getFotografia()));
        checkSociosEstado.setSelected(member.getEstado());
    }
}
