/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFrame;
import myassociation.controller.AssociationController;
import myassociation.controller.UserController;
import myassociation.dal.ConnectDB;
import myassociation.model.Application;
import myassociation.model.Association;

/**
 *
 * @author FELGUEIRAS
 */
public class Login extends javax.swing.JFrame {

    private static final long serialVersionUID = -3073256603988980690L;

    private final ConnectDB conexao;
    private AssociationController assocController;
    private UserController usercontroller;
    private Application app;
    private File file = new File(System.getProperty("user.home") + "/MyAssociationdata.txt");

    /**
     * Creates new form Login
     *
     * @param application
     */
    public Login(Application application) {
        initComponents();
        this.setLocationRelativeTo(null);
        loadLogin();
        conexao = new ConnectDB();
        this.app = application;
        assocController = new AssociationController();
        usercontroller = new UserController();
        this.getRootPane().setDefaultButton(btnEntrar);
        this.setIconImage(assocController.applicationIcon());
        setAssociationName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jplMain = new javax.swing.JPanel();
        jplLeft = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblAssociationName = new javax.swing.JLabel();
        jplClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        txtUtilizador = new javax.swing.JTextField();
        lblUtilizador = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        pwdSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        chkLogin = new javax.swing.JCheckBox();
        jplMinimze = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("loginfrm"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplMain.setLayout(null);

        jplLeft.setBackground(new java.awt.Color(0, 98, 206));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/login_images/login_icon.PNG"))); // NOI18N

        lblAssociationName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAssociationName.setForeground(new java.awt.Color(255, 255, 255));
        lblAssociationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAssociationName.setText("MyAssociation");

        javax.swing.GroupLayout jplLeftLayout = new javax.swing.GroupLayout(jplLeft);
        jplLeft.setLayout(jplLeftLayout);
        jplLeftLayout.setHorizontalGroup(
            jplLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAssociationName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplLeftLayout.createSequentialGroup()
                .addGap(60, 62, Short.MAX_VALUE)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jplLeftLayout.setVerticalGroup(
            jplLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLeftLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAssociationName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jplMain.add(jplLeft);
        jplLeft.setBounds(0, 0, 292, 390);

        jplClose.setBackground(new java.awt.Color(0, 98, 206));

        lblClose.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setName(""); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jplCloseLayout = new javax.swing.GroupLayout(jplClose);
        jplClose.setLayout(jplCloseLayout);
        jplCloseLayout.setHorizontalGroup(
            jplCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jplCloseLayout.setVerticalGroup(
            jplCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jplMain.add(jplClose);
        jplClose.setBounds(587, 0, 30, 33);

        lblSignUp.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(102, 102, 102));
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("Autenticação");
        jplMain.add(lblSignUp);
        lblSignUp.setBounds(350, 50, 200, 50);

        txtUtilizador.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUtilizador.setForeground(new java.awt.Color(51, 51, 51));
        txtUtilizador.setBorder(null);
        jplMain.add(txtUtilizador);
        txtUtilizador.setBounds(320, 130, 260, 40);

        lblUtilizador.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUtilizador.setForeground(new java.awt.Color(51, 51, 51));
        lblUtilizador.setText("Utilizador");
        jplMain.add(lblUtilizador);
        lblUtilizador.setBounds(320, 110, 60, 16);

        lblSenha.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(51, 51, 51));
        lblSenha.setText("Senha");
        jplMain.add(lblSenha);
        lblSenha.setBounds(320, 190, 60, 16);

        pwdSenha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pwdSenha.setForeground(new java.awt.Color(51, 51, 51));
        pwdSenha.setBorder(null);
        jplMain.add(pwdSenha);
        pwdSenha.setBounds(320, 210, 260, 40);

        btnEntrar.setBackground(new java.awt.Color(0, 98, 206));
        btnEntrar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jplMain.add(btnEntrar);
        btnEntrar.setBounds(400, 310, 110, 40);

        lblMessage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 51, 51));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jplMain.add(lblMessage);
        lblMessage.setBounds(320, 350, 270, 30);

        chkLogin.setBackground(new java.awt.Color(255, 255, 255));
        chkLogin.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chkLogin.setForeground(new java.awt.Color(51, 51, 51));
        chkLogin.setText("Lembrar-me");
        chkLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkLoginMouseReleased(evt);
            }
        });
        jplMain.add(chkLogin);
        chkLogin.setBounds(320, 270, 100, 23);

        jplMinimze.setBackground(new java.awt.Color(0, 98, 206));

        lblMinimize.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jplMinimzeLayout = new javax.swing.GroupLayout(jplMinimze);
        jplMinimze.setLayout(jplMinimzeLayout);
        jplMinimzeLayout.setHorizontalGroup(
            jplMinimzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMinimzeLayout.createSequentialGroup()
                .addComponent(lblMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        jplMinimzeLayout.setVerticalGroup(
            jplMinimzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jplMain.add(jplMinimze);
        jplMinimze.setBounds(560, 0, 30, 33);

        jSeparator1.setBackground(new java.awt.Color(0, 98, 206));
        jSeparator1.setForeground(new java.awt.Color(0, 98, 206));
        jplMain.add(jSeparator1);
        jSeparator1.setBounds(320, 250, 260, 10);

        jSeparator2.setBackground(new java.awt.Color(0, 98, 206));
        jSeparator2.setForeground(new java.awt.Color(0, 98, 206));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 3));
        jplMain.add(jSeparator2);
        jSeparator2.setBounds(320, 170, 260, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(617, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseReleased
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseReleased

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String username = txtUtilizador.getText();
        boolean login = usercontroller.pesquisaLogin(username, String.valueOf(pwdSenha.getPassword()));

        if (login == true) {
            app.setCurrentUser(username);
            new Main(username).setVisible(true);
            System.out.println("Login: " + username);
            this.dispose();
        } else {
            txtUtilizador.setText("");
            pwdSenha.setText("");
            lblMessage.setText("O utilizador/senha é inválido.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseReleased
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseReleased

    private void chkLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkLoginMouseReleased
        saveLogin();
    }//GEN-LAST:event_chkLoginMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login(new Application()).setVisible(true);
            }
        });
    }

    public void saveLogin() {

        try {
            if (!file.exists()) {
                file.createNewFile();
            }
            BufferedWriter bw = new BufferedWriter(new FileWriter(file.getAbsolutePath()));
            bw.write(txtUtilizador.getText());
            bw.close();

        } catch (IOException e) {
            e.getMessage();
        }

    }

    private void loadLogin() {

        try {
            if (file.exists()) {

                Scanner scan = new Scanner(file);
                if (scan.hasNext()) {
                    txtUtilizador.setText(scan.nextLine());
                }
                scan.close();
            }

        } catch (FileNotFoundException e) {
            e.getMessage();
        }
    }

    private void setAssociationName() {
        try {
            Association nomeAssociacao = assocController.obterAssociacao();
            lblAssociationName.setText(nomeAssociacao.getNome());
        } catch (NullPointerException ex) {
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox chkLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jplClose;
    private javax.swing.JPanel jplLeft;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplMinimze;
    private javax.swing.JLabel lblAssociationName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblUtilizador;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtUtilizador;
    // End of variables declaration//GEN-END:variables

}
