/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.awt.CardLayout;
import java.awt.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import myassociation.controller.AssociationController;
import myassociation.controller.MemberController;
import myassociation.controller.UserController;
import myassociation.model.Association;
import myassociation.model.Member;
import myassociation.model.User;

/**
 *
 * @author FELGUEIRAS
 */
public class Main extends javax.swing.JFrame {

    private static final long serialVersionUID = 605867281338758257L;

    private AssociationController assocController;
    private UserController utilizadorController;
    private MemberController socioController;
    private javax.swing.table.DefaultTableModel tabelasocios = new javax.swing.table.DefaultTableModel(new String[]{"Numero", "NIF", "Nome", "Telefone", "Telemovel", "Morada", "Email", "Data criação", "Data modificação", "Utilizador", "Categoria"}, 0);
    private javax.swing.table.DefaultTableModel tableusers = new javax.swing.table.DefaultTableModel(new String[]{"Utilizador", "Data criacao", "Data modificacao", "Grupo", "Associacao"}, 0);
    private final Object[] joptionpaneoptions = {"Sim", "Não"};
    private Point initialClick;
    private String username;

    /**
     * Creates new form Main
     *
     * @param username
     */
    public Main(String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        assocController = new AssociationController();
        utilizadorController = new UserController();
        socioController = new MemberController();
        setAssociationName();
        this.username = username;
        lblusername.setText(username);
        txtHomeTotalSocios.setText(socioController.totalSociosAtivos());
        tblSocios.setModel(tabelasocios);
        tblSocios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsers.setModel(tableusers);
        tblUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblQuotas.setModel(tabelasocios);
        tblQuotas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.setIconImage(assocController.applicationIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplBase = new javax.swing.JPanel();
        jplTop = new javax.swing.JPanel();
        jplMinimize = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        jplClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblNomeAssociacao = new javax.swing.JLabel();
        lblAjuda = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblCalculadora = new javax.swing.JLabel();
        lblCalculator = new javax.swing.JLabel();
        lblDefinicoes = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        jplSideBar = new javax.swing.JPanel();
        jplUtilizadores = new javax.swing.JPanel();
        lblBotaoUtilizadores = new javax.swing.JLabel();
        lblUtilizadoresDescricao = new javax.swing.JLabel();
        jplSocios = new javax.swing.JPanel();
        lblBotaoSocios = new javax.swing.JLabel();
        lblSociosDescricao = new javax.swing.JLabel();
        jplQuotas = new javax.swing.JPanel();
        lblBotaoQuotas = new javax.swing.JLabel();
        lblQuotasDescricao = new javax.swing.JLabel();
        jplModalidades = new javax.swing.JPanel();
        lblBotaoModalidades = new javax.swing.JLabel();
        lblModalidadesDescricao = new javax.swing.JLabel();
        jplListagens = new javax.swing.JPanel();
        lblBotaoListagens = new javax.swing.JLabel();
        lblListagensDescricao = new javax.swing.JLabel();
        jplCardBase = new javax.swing.JPanel();
        jplCardHome = new javax.swing.JPanel();
        lblSociosTitulo = new javax.swing.JLabel();
        lblHomeSociosativos = new javax.swing.JLabel();
        txtHomeTotalSocios = new javax.swing.JTextField();
        lblola = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jplCardSocios = new javax.swing.JPanel();
        jplSocBarraFerramentas = new javax.swing.JPanel();
        lblSocBtnCriarSocio = new javax.swing.JLabel();
        lblSocTitulo = new javax.swing.JLabel();
        lblSocNovo = new javax.swing.JLabel();
        lblSocBtnAlterarSocio = new javax.swing.JLabel();
        lblSocEditar = new javax.swing.JLabel();
        lblSocBtnDesativar = new javax.swing.JLabel();
        lblSocInativar = new javax.swing.JLabel();
        lblSocBtnCartao = new javax.swing.JLabel();
        lblSocRenumerar = new javax.swing.JLabel();
        lblSocBtnApagar = new javax.swing.JLabel();
        lblSocCartao1 = new javax.swing.JLabel();
        lblSocBtnRenumerar = new javax.swing.JLabel();
        lblSocRemover1 = new javax.swing.JLabel();
        lblSocBtnCategoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jplSocTabela = new javax.swing.JPanel();
        lblSocPesquisar = new javax.swing.JLabel();
        jcbSocPesquisar = new javax.swing.JComboBox<>();
        txtSocPesquisar = new javax.swing.JTextField();
        scrollSocios = new javax.swing.JScrollPane();
        tblSocios = new javax.swing.JTable();
        lblSocValidar = new javax.swing.JLabel();
        btnRadioSocInativos = new javax.swing.JRadioButton();
        jplCardQuotas = new javax.swing.JPanel();
        jplQuotasBarraFerramentas = new javax.swing.JPanel();
        lblQuoBtnPagarQuotas = new javax.swing.JLabel();
        lblQuotasTitulo = new javax.swing.JLabel();
        lblQuoPagar = new javax.swing.JLabel();
        lblQuoBtnImprimir = new javax.swing.JLabel();
        lblQuoImprimir = new javax.swing.JLabel();
        lblQuoBtnConsultar = new javax.swing.JLabel();
        lblQuoConsultar = new javax.swing.JLabel();
        jplSocQuotasTabela = new javax.swing.JPanel();
        lblQuotasPesquisar = new javax.swing.JLabel();
        jcbQuotasPesquisar = new javax.swing.JComboBox<>();
        txtQuotasPesquisar = new javax.swing.JTextField();
        btnRadioQuotasInativos = new javax.swing.JRadioButton();
        lblQuotasValidar = new javax.swing.JLabel();
        scrollQuotas = new javax.swing.JScrollPane();
        tblQuotas = new javax.swing.JTable();
        jplCardUtilizadores = new javax.swing.JPanel();
        jplListaUtilizadores = new javax.swing.JPanel();
        lblUtilPesquisar = new javax.swing.JLabel();
        txtUserSearch = new javax.swing.JTextField();
        lblUtilValidar = new javax.swing.JLabel();
        scrollUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jcbUserSearch = new javax.swing.JComboBox<>();
        jplUtilBarraFerramentas = new javax.swing.JPanel();
        lblUtilBtnCriarUtil = new javax.swing.JLabel();
        lblUtilNovo = new javax.swing.JLabel();
        lblUtilBtnAlterarUtil = new javax.swing.JLabel();
        lblUtilEditar = new javax.swing.JLabel();
        lblUtilBtnRemoverUtil = new javax.swing.JLabel();
        lblUtilRemover = new javax.swing.JLabel();
        lblUtilTitulo = new javax.swing.JLabel();
        jplCardListagens = new javax.swing.JPanel();
        lblListagensTitulo = new javax.swing.JLabel();
        jplCardEstatisticas = new javax.swing.JPanel();
        lblEstatisticasTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setName("frmMain"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jplBase.setBackground(new java.awt.Color(255, 255, 255));
        jplBase.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 3, new java.awt.Color(0, 98, 206)));
        jplBase.setForeground(new java.awt.Color(255, 255, 255));
        jplBase.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jplBaseMouseDragged(evt);
            }
        });
        jplBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jplBaseMousePressed(evt);
            }
        });

        jplTop.setBackground(new java.awt.Color(0, 98, 206));
        jplTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplMinimize.setBackground(new java.awt.Color(0, 98, 206));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jplMinimizeLayout = new javax.swing.GroupLayout(jplMinimize);
        jplMinimize.setLayout(jplMinimizeLayout);
        jplMinimizeLayout.setHorizontalGroup(
            jplMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        jplMinimizeLayout.setVerticalGroup(
            jplMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jplTop.add(jplMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 0, -1, -1));

        jplClose.setBackground(new java.awt.Color(0, 98, 206));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jplCloseLayout = new javax.swing.GroupLayout(jplClose);
        jplClose.setLayout(jplCloseLayout);
        jplCloseLayout.setHorizontalGroup(
            jplCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCloseLayout.createSequentialGroup()
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jplCloseLayout.setVerticalGroup(
            jplCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jplTop.add(jplClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, -1, -1));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app_images/White_MyAssociationLogo_100px.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoMousePressed(evt);
            }
        });
        jplTop.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 114, 90));

        lblNomeAssociacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeAssociacao.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeAssociacao.setText("MyAssociation");
        jplTop.add(lblNomeAssociacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 52, 340, -1));

        lblAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Utils_Ajuda_40px.png"))); // NOI18N
        lblAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAjudaMousePressed(evt);
            }
        });
        jplTop.add(lblAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1216, 30, 45, 40));

        lblAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbout.setText("Ajuda");
        jplTop.add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1216, 75, 45, -1));

        lblCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Utils_Calculadora_40px.png"))); // NOI18N
        lblCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCalculadoraMousePressed(evt);
            }
        });
        jplTop.add(lblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 50, 40));

        lblCalculator.setForeground(new java.awt.Color(255, 255, 255));
        lblCalculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculator.setText("Calculadora");
        jplTop.add(lblCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 75, -1, -1));

        lblDefinicoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDefinicoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Utils_Definicoes_40px.png"))); // NOI18N
        lblDefinicoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDefinicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDefinicoesMousePressed(evt);
            }
        });
        jplTop.add(lblDefinicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 30, 45, 40));

        lblSettings.setForeground(new java.awt.Color(255, 255, 255));
        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setText("Definições");
        jplTop.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1067, 75, 60, -1));

        jplSideBar.setBackground(new java.awt.Color(255, 255, 255));
        jplSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplUtilizadores.setBackground(new java.awt.Color(255, 255, 255));
        jplUtilizadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBotaoUtilizadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotaoUtilizadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Menu_Utilizadores_64px.png"))); // NOI18N
        lblBotaoUtilizadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoUtilizadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoUtilizadoresMousePressed(evt);
            }
        });
        jplUtilizadores.add(lblBotaoUtilizadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 56));

        lblUtilizadoresDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilizadoresDescricao.setForeground(new java.awt.Color(45, 118, 232));
        lblUtilizadoresDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilizadoresDescricao.setText("UTILIZADORES");
        jplUtilizadores.add(lblUtilizadoresDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 97, -1));

        jplSideBar.add(jplUtilizadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 90));

        jplSocios.setBackground(new java.awt.Color(255, 255, 255));
        jplSocios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBotaoSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotaoSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Menu_Socios_64px.png"))); // NOI18N
        lblBotaoSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoSociosMousePressed(evt);
            }
        });
        jplSocios.add(lblBotaoSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, 47));

        lblSociosDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosDescricao.setForeground(new java.awt.Color(45, 118, 232));
        lblSociosDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSociosDescricao.setText("SÓCIOS");
        jplSocios.add(lblSociosDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 100, -1));

        jplSideBar.add(jplSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, -1));

        jplQuotas.setBackground(new java.awt.Color(255, 255, 255));
        jplQuotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBotaoQuotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotaoQuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Menu_Quotas_64px.png"))); // NOI18N
        lblBotaoQuotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoQuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoQuotasMousePressed(evt);
            }
        });
        jplQuotas.add(lblBotaoQuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 53, 45));

        lblQuotasDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuotasDescricao.setForeground(new java.awt.Color(45, 118, 232));
        lblQuotasDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuotasDescricao.setText("QUOTAS");
        jplQuotas.add(lblQuotasDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 67, 53, -1));

        jplSideBar.add(jplQuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, -1));

        jplModalidades.setBackground(new java.awt.Color(255, 255, 255));
        jplModalidades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBotaoModalidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotaoModalidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Menu_Modalidades_64px.png"))); // NOI18N
        lblBotaoModalidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoModalidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoModalidadesMousePressed(evt);
            }
        });
        jplModalidades.add(lblBotaoModalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 56));

        lblModalidadesDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModalidadesDescricao.setForeground(new java.awt.Color(45, 118, 232));
        lblModalidadesDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModalidadesDescricao.setText("MODALIDADES");
        jplModalidades.add(lblModalidadesDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 98, -1));

        jplSideBar.add(jplModalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 90));

        jplListagens.setBackground(new java.awt.Color(255, 255, 255));
        jplListagens.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBotaoListagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Menu_Listagens_64px.png"))); // NOI18N
        lblBotaoListagens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoListagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBotaoListagensMousePressed(evt);
            }
        });
        jplListagens.add(lblBotaoListagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, 56));

        lblListagensDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblListagensDescricao.setForeground(new java.awt.Color(45, 118, 232));
        lblListagensDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListagensDescricao.setText("LISTAGENS");
        jplListagens.add(lblListagensDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, -1));

        jplSideBar.add(jplListagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 100, 90));

        jplCardBase.setBackground(new java.awt.Color(255, 255, 255));
        jplCardBase.setLayout(new java.awt.CardLayout());

        jplCardHome.setBackground(new java.awt.Color(246, 246, 246));
        jplCardHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSociosTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSociosTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSociosTitulo.setText("HOME");
        jplCardHome.add(lblSociosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 1190, -1));

        lblHomeSociosativos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHomeSociosativos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeSociosativos.setText("Total sócios ativos:");
        lblHomeSociosativos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206)));
        jplCardHome.add(lblHomeSociosativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 130, 30));
        lblHomeSociosativos.getAccessibleContext().setAccessibleName("lblSociosativos");

        txtHomeTotalSocios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHomeTotalSocios.setForeground(new java.awt.Color(51, 204, 0));
        txtHomeTotalSocios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHomeTotalSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206)));
        txtHomeTotalSocios.setDisabledTextColor(new java.awt.Color(51, 204, 0));
        txtHomeTotalSocios.setEnabled(false);
        jplCardHome.add(txtHomeTotalSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 50, 30));

        lblola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblola.setForeground(new java.awt.Color(0, 98, 206));
        lblola.setText("Olá");
        jplCardHome.add(lblola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        lblusername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusername.setForeground(new java.awt.Color(0, 98, 206));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblusername.setPreferredSize(new java.awt.Dimension(64, 14));
        jplCardHome.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 30));

        jplCardBase.add(jplCardHome, "jplCardHome");

        jplCardSocios.setBackground(new java.awt.Color(246, 246, 246));
        jplCardSocios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplSocBarraFerramentas.setBackground(new java.awt.Color(246, 246, 246));
        jplSocBarraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSocBarraFerramentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSocBtnCriarSocio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnCriarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Novo_50px.png"))); // NOI18N
        lblSocBtnCriarSocio.setPreferredSize(new java.awt.Dimension(40, 40));
        lblSocBtnCriarSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnCriarSocioMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnCriarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 54, 52));

        lblSocTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSocTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblSocTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocTitulo.setText("SÓCIOS");
        jplSocBarraFerramentas.add(lblSocTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        lblSocNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSocNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocNovo.setText("Novo");
        jplSocBarraFerramentas.add(lblSocNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 54, -1));

        lblSocBtnAlterarSocio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnAlterarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Editar_50px.png"))); // NOI18N
        lblSocBtnAlterarSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnAlterarSocioMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnAlterarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 54, 52));

        lblSocEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSocEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocEditar.setText("Editar");
        jplSocBarraFerramentas.add(lblSocEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 54, -1));

        lblSocBtnDesativar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnDesativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Desativar_50px.png"))); // NOI18N
        lblSocBtnDesativar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSocBtnDesativar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnDesativarMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnDesativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 52));

        lblSocInativar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSocInativar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocInativar.setText("Inativar");
        jplSocBarraFerramentas.add(lblSocInativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        lblSocBtnCartao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_imprimir_cartao_50px.png"))); // NOI18N
        lblSocBtnCartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnCartaoMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 54, 52));

        lblSocRenumerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSocRenumerar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocRenumerar.setText("Renumerar");
        jplSocBarraFerramentas.add(lblSocRenumerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, -1));

        lblSocBtnApagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Apagar_50px.png"))); // NOI18N
        lblSocBtnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnApagarMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 54, 52));

        lblSocCartao1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSocCartao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocCartao1.setText("Cartão");
        jplSocBarraFerramentas.add(lblSocCartao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 54, -1));

        lblSocBtnRenumerar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnRenumerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Renumerar_50px.png"))); // NOI18N
        lblSocBtnRenumerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnRenumerarMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnRenumerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 54, 52));

        lblSocRemover1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSocRemover1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocRemover1.setText("Apagar");
        jplSocBarraFerramentas.add(lblSocRemover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 54, -1));

        lblSocBtnCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocBtnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Categoria_50px.png"))); // NOI18N
        lblSocBtnCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocBtnCategoriaMousePressed(evt);
            }
        });
        jplSocBarraFerramentas.add(lblSocBtnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 54, 52));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categoria");
        jplSocBarraFerramentas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 70, 60, -1));

        jplCardSocios.add(jplSocBarraFerramentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1194, -1));

        jplSocTabela.setBackground(new java.awt.Color(246, 246, 246));
        jplSocTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jplSocTabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSocPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSocPesquisar.setText("Pesquisar:");
        jplSocTabela.add(lblSocPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 103, 37));

        jcbSocPesquisar.setBackground(new java.awt.Color(240, 240, 240));
        jcbSocPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbSocPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Numero", "NIF", "Telefone", "Telemovel", "Morada", "Email" }));
        jcbSocPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSocTabela.add(jcbSocPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 12, 149, 37));
        jplSocTabela.add(txtSocPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 11, 755, 38));

        tblSocios.setBackground(new java.awt.Color(246, 246, 246));
        tblSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        scrollSocios.setViewportView(tblSocios);

        jplSocTabela.add(scrollSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1194, 575));

        lblSocValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Filtrar_40px.png"))); // NOI18N
        lblSocValidar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSocValidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSocValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocValidarMousePressed(evt);
            }
        });
        jplSocTabela.add(lblSocValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 11, -1, 38));

        btnRadioSocInativos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRadioSocInativos.setText("Inativos");
        btnRadioSocInativos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSocTabela.add(btnRadioSocInativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1023, 18, 97, -1));

        jplCardSocios.add(jplSocTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, -1, 635));

        jplCardBase.add(jplCardSocios, "jplCardSocios");

        jplCardQuotas.setBackground(new java.awt.Color(246, 246, 246));
        jplCardQuotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplQuotasBarraFerramentas.setBackground(new java.awt.Color(246, 246, 246));
        jplQuotasBarraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplQuotasBarraFerramentas.setPreferredSize(new java.awt.Dimension(1190, 85));
        jplQuotasBarraFerramentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuoBtnPagarQuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Quotas_Pagar_50px.png"))); // NOI18N
        lblQuoBtnPagarQuotas.setPreferredSize(new java.awt.Dimension(40, 40));
        lblQuoBtnPagarQuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuoBtnPagarQuotasMousePressed(evt);
            }
        });
        jplQuotasBarraFerramentas.add(lblQuoBtnPagarQuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 54, 52));

        lblQuotasTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuotasTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblQuotasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuotasTitulo.setText("QUOTAS");
        jplQuotasBarraFerramentas.add(lblQuotasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1194, -1));

        lblQuoPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuoPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuoPagar.setText("Pagar");
        jplQuotasBarraFerramentas.add(lblQuoPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 54, -1));

        lblQuoBtnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuoBtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Quotas_imprimir_50px.png"))); // NOI18N
        jplQuotasBarraFerramentas.add(lblQuoBtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 54, 52));

        lblQuoImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuoImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuoImprimir.setText("Imprimir");
        jplQuotasBarraFerramentas.add(lblQuoImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 54, -1));

        lblQuoBtnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuoBtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Quotas_Consultar_50px.png"))); // NOI18N
        lblQuoBtnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplQuotasBarraFerramentas.add(lblQuoBtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 54, 52));

        lblQuoConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuoConsultar.setText("Consultar");
        jplQuotasBarraFerramentas.add(lblQuoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 60, -1));

        jplCardQuotas.add(jplQuotasBarraFerramentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1194, -1));

        jplSocQuotasTabela.setBackground(new java.awt.Color(246, 246, 246));
        jplSocQuotasTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jplSocQuotasTabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuotasPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuotasPesquisar.setText("Pesquisar:");
        jplSocQuotasTabela.add(lblQuotasPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 103, 37));

        jcbQuotasPesquisar.setBackground(new java.awt.Color(240, 240, 240));
        jcbQuotasPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbQuotasPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Numero", "NIF", "Telefone", "Telemovel", "Morada", "Email", " " }));
        jcbQuotasPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSocQuotasTabela.add(jcbQuotasPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 12, 149, 37));
        jplSocQuotasTabela.add(txtQuotasPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 11, 755, 38));

        btnRadioQuotasInativos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRadioQuotasInativos.setText("Inativos");
        btnRadioQuotasInativos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplSocQuotasTabela.add(btnRadioQuotasInativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1023, 18, 97, -1));

        lblQuotasValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Filtrar_40px.png"))); // NOI18N
        lblQuotasValidar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblQuotasValidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuotasValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuotasValidarMousePressed(evt);
            }
        });
        jplSocQuotasTabela.add(lblQuotasValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 11, -1, 38));

        scrollQuotas.setBackground(new java.awt.Color(246, 246, 246));

        tblQuotas.setBackground(new java.awt.Color(246, 246, 246));
        tblQuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        scrollQuotas.setViewportView(tblQuotas);

        jplSocQuotasTabela.add(scrollQuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1194, 580));

        jplCardQuotas.add(jplSocQuotasTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, -1, -1));

        jplCardBase.add(jplCardQuotas, "jplCardQuotas");

        jplCardUtilizadores.setBackground(new java.awt.Color(246, 246, 246));
        jplCardUtilizadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplListaUtilizadores.setBackground(new java.awt.Color(246, 246, 246));
        jplListaUtilizadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUtilPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUtilPesquisar.setText("Pesquisar:");
        jplListaUtilizadores.add(lblUtilPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 103, 37));
        jplListaUtilizadores.add(txtUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 12, 850, 37));

        lblUtilValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Filtrar_40px.png"))); // NOI18N
        lblUtilValidar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblUtilValidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUtilValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUtilValidarMousePressed(evt);
            }
        });
        jplListaUtilizadores.add(lblUtilValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 12, -1, 37));

        tblUsers.setBackground(new java.awt.Color(246, 246, 246));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        scrollUsers.setViewportView(tblUsers);

        jplListaUtilizadores.add(scrollUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1194, 580));

        jcbUserSearch.setBackground(new java.awt.Color(240, 240, 240));
        jcbUserSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbUserSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilizador", "Grupo Utilizador", "Associacao" }));
        jcbUserSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplListaUtilizadores.add(jcbUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 12, 149, 37));

        jplCardUtilizadores.add(jplListaUtilizadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, -1, -1));

        jplUtilBarraFerramentas.setBackground(new java.awt.Color(246, 246, 246));
        jplUtilBarraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplUtilBarraFerramentas.setPreferredSize(new java.awt.Dimension(1190, 85));
        jplUtilBarraFerramentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUtilBtnCriarUtil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Novo_50px.png"))); // NOI18N
        lblUtilBtnCriarUtil.setPreferredSize(new java.awt.Dimension(40, 40));
        lblUtilBtnCriarUtil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUtilBtnCriarUtilMousePressed(evt);
            }
        });
        jplUtilBarraFerramentas.add(lblUtilBtnCriarUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 54, 52));

        lblUtilNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilNovo.setText("Novo");
        lblUtilNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jplUtilBarraFerramentas.add(lblUtilNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 54, 20));

        lblUtilBtnAlterarUtil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Editar_50px.png"))); // NOI18N
        jplUtilBarraFerramentas.add(lblUtilBtnAlterarUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 54, 52));

        lblUtilEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilEditar.setText("Editar");
        lblUtilEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jplUtilBarraFerramentas.add(lblUtilEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 54, 20));

        lblUtilBtnRemoverUtil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Socios_Desativar_50px.png"))); // NOI18N
        lblUtilBtnRemoverUtil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplUtilBarraFerramentas.add(lblUtilBtnRemoverUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 54, 52));

        lblUtilRemover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUtilRemover.setText("Remover");
        lblUtilRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jplUtilBarraFerramentas.add(lblUtilRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 20));

        lblUtilTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUtilTitulo.setForeground(new java.awt.Color(45, 118, 232));
        lblUtilTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilTitulo.setText("UTILIZADORES");
        jplUtilBarraFerramentas.add(lblUtilTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1182, -1));

        jplCardUtilizadores.add(jplUtilBarraFerramentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1194, -1));

        jplCardBase.add(jplCardUtilizadores, "jplCardUtilizadores");

        jplCardListagens.setBackground(new java.awt.Color(246, 246, 246));
        jplCardListagens.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListagensTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListagensTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblListagensTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListagensTitulo.setText("LISTAGENS");
        jplCardListagens.add(lblListagensTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        jplCardBase.add(jplCardListagens, "jplCardListagens");

        jplCardEstatisticas.setBackground(new java.awt.Color(246, 246, 246));
        jplCardEstatisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstatisticasTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstatisticasTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblEstatisticasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatisticasTitulo.setText("ESTATÍSTICAS");
        jplCardEstatisticas.add(lblEstatisticasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        jplCardBase.add(jplCardEstatisticas, "jplCardEstatisticas");

        javax.swing.GroupLayout jplBaseLayout = new javax.swing.GroupLayout(jplBase);
        jplBase.setLayout(jplBaseLayout);
        jplBaseLayout.setHorizontalGroup(
            jplBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jplBaseLayout.createSequentialGroup()
                .addComponent(jplSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplBaseLayout.setVerticalGroup(
            jplBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplBaseLayout.createSequentialGroup()
                .addComponent(jplTop, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jplSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jplCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jplBase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBotaoSociosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoSociosMousePressed
        CardLayout card = (CardLayout) jplCardBase.getLayout();
        card.show(jplCardBase, "jplCardSocios");
        setColor(jplSocios);
        resetColor(jplQuotas);
        resetColor(jplUtilizadores);
        resetColor(jplModalidades);
        resetColor(jplListagens);
    }//GEN-LAST:event_lblBotaoSociosMousePressed

    private void lblBotaoQuotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoQuotasMousePressed
        CardLayout card = (CardLayout) jplCardBase.getLayout();
        card.show(jplCardBase, "jplCardQuotas");
        setColor(jplQuotas);
        resetColor(jplSocios);
        resetColor(jplUtilizadores);
        resetColor(jplModalidades);
        resetColor(jplListagens);
    }//GEN-LAST:event_lblBotaoQuotasMousePressed

    private void lblBotaoUtilizadoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoUtilizadoresMousePressed
        CardLayout card = (CardLayout) jplCardBase.getLayout();
        card.show(jplCardBase, "jplCardUtilizadores");
        setColor(jplUtilizadores);
        resetColor(jplQuotas);
        resetColor(jplSocios);
        resetColor(jplModalidades);
        resetColor(jplListagens);
    }//GEN-LAST:event_lblBotaoUtilizadoresMousePressed

    private void lblBotaoListagensMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoListagensMousePressed
        CardLayout card = (CardLayout) jplCardBase.getLayout();
        card.show(jplCardBase, "jplCardListagens");
        setColor(jplModalidades);
        resetColor(jplQuotas);
        resetColor(jplSocios);
        resetColor(jplCardQuotas);
        resetColor(jplUtilizadores);
        resetColor(jplListagens);
    }//GEN-LAST:event_lblBotaoListagensMousePressed

    private void lblBotaoModalidadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoModalidadesMousePressed
        CardLayout card = (CardLayout) jplCardBase.getLayout();
        card.show(jplCardBase, "jplCardEstatisticas");
        setColor(jplListagens);
        resetColor(jplQuotas);
        resetColor(jplSocios);
        resetColor(jplCardQuotas);
        resetColor(jplUtilizadores);
        resetColor(jplModalidades);

    }//GEN-LAST:event_lblBotaoModalidadesMousePressed

    private void jplBaseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplBaseMouseDragged
        try {
            // get location of Window
            int thisX = this.getLocation().x;
            int thisY = this.getLocation().y;

            // Determine how much the mouse moved since the initial click
            int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
            int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

            // Move window to this position
            int X = thisX + xMoved;
            int Y = thisY + yMoved;
            this.setLocation(X, Y);
        } catch (NullPointerException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_jplBaseMouseDragged

    private void jplBaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplBaseMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_jplBaseMousePressed

    private void lblSocBtnCriarSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnCriarSocioMousePressed
        new CreateMember(username).setVisible(true);
    }//GEN-LAST:event_lblSocBtnCriarSocioMousePressed

    private void lblSocValidarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocValidarMousePressed
        tabelasocios.setRowCount(0);

        ArrayList<Member> socioPesquisado = socioController.pesquisarSocio((String) jcbSocPesquisar.getSelectedItem(), txtSocPesquisar.getText(), !btnRadioSocInativos.isSelected());
        if (socioPesquisado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "0 resultados encontrados para a pesquisada efetuada.", "Resultados", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i = 0; i < socioPesquisado.size(); i++) {
                tabelasocios.addRow(new Object[]{socioPesquisado.get(i).getNumero(), socioPesquisado.get(i).getNif(), socioPesquisado.get(i).getNome(), socioPesquisado.get(i).getTelefone(), socioPesquisado.get(i).getTelemovel(), socioPesquisado.get(i).getMorada(), socioPesquisado.get(i).getEmail(), socioPesquisado.get(i).getDatacriacao(), socioPesquisado.get(i).getDatamodif(), socioPesquisado.get(i).getUtilizador(), socioPesquisado.get(i).getCategoria()});
            }
        }
        tabelasocios.fireTableDataChanged();
    }//GEN-LAST:event_lblSocValidarMousePressed

    private void lblCalculadoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMousePressed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblCalculadoraMousePressed

    private void lblAjudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAjudaMousePressed
        new About().setVisible(true);
    }//GEN-LAST:event_lblAjudaMousePressed

    private void lblLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMousePressed
        CardLayout card = (CardLayout) jplCardBase.getLayout();
        card.show(jplCardBase, "jplCardHome");
    }//GEN-LAST:event_lblLogoMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair da aplicação?",
                "Fechar aplicação",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblUtilBtnCriarUtilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilBtnCriarUtilMousePressed
        new CreateUser().setVisible(true);
    }//GEN-LAST:event_lblUtilBtnCriarUtilMousePressed

    private void lblQuoBtnPagarQuotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuoBtnPagarQuotasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuoBtnPagarQuotasMousePressed

    private void lblSocBtnAlterarSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnAlterarSocioMousePressed
        try {
            Member socio = socioController.pesquisarSocioPorNumero(tabelasocios.getValueAt(tblSocios.getSelectedRow(), 0).toString());
            new EditMember(socio, username).setVisible(true);
        } catch (java.lang.ArrayIndexOutOfBoundsException execp) {
            JOptionPane.showMessageDialog(this, "Nenhum sócio seleccionado para edição. \nEfetue uma pesquisa primeiro.", "Impossivel alterar", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_lblSocBtnAlterarSocioMousePressed

    private void lblSocBtnDesativarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnDesativarMousePressed
        try {
            Object socio = tblSocios.getValueAt(tblSocios.getSelectedRow(), 0);
            String numero = socio.toString();
            int selectedOption = JOptionPane.showOptionDialog(this,
                    "Desenha mesmo inativar o sócio seleccionado?",
                    "Inativar sócio",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    joptionpaneoptions,
                    joptionpaneoptions[1]);
            if (selectedOption == JOptionPane.YES_OPTION) {
                boolean retorno = socioController.inativarSocio(numero);
                if (retorno == true) {
                    JOptionPane.showMessageDialog(this, "Sócio com o numero " + numero + " inativado com sucesso.", "Desativar sócio", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Desativação impossível.", "Inativar sócio", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Nenhum sócio seleccionado para desativação. \nEfetue uma pesquisa primeiro.", "Impossivel desativar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lblSocBtnDesativarMousePressed

    private void lblSocBtnCartaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnCartaoMousePressed
        try {
            Member socio = socioController.pesquisarSocioPorNumero(tabelasocios.getValueAt(tblSocios.getSelectedRow(), 0).toString());
            new ViewMember(socio).setVisible(true);
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (java.lang.ArrayIndexOutOfBoundsException execp) {
            JOptionPane.showMessageDialog(this, "Nenhum sócio seleccionado para edição. \nEfetue uma pesquisa primeiro.", "Impossivel alterar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lblSocBtnCartaoMousePressed

    private void lblQuotasValidarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuotasValidarMousePressed
        tabelasocios.setRowCount(0);

        ArrayList<Member> socioPesquisado = socioController.pesquisarSocio((String) jcbSocPesquisar.getSelectedItem(), txtSocPesquisar.getText(), !btnRadioSocInativos.isSelected());
        if (socioPesquisado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "0 resultados encontrados para a pesquisada efetuada.", "Resultados", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i = 0; i < socioPesquisado.size(); i++) {
                tabelasocios.addRow(new Object[]{socioPesquisado.get(i).getNumero(), socioPesquisado.get(i).getNif(), socioPesquisado.get(i).getNome(), socioPesquisado.get(i).getTelefone(), socioPesquisado.get(i).getTelemovel(), socioPesquisado.get(i).getMorada(), socioPesquisado.get(i).getEmail(), socioPesquisado.get(i).getDatacriacao(), socioPesquisado.get(i).getDatamodif()});
            }
        }
        tabelasocios.fireTableDataChanged();
    }//GEN-LAST:event_lblQuotasValidarMousePressed

    private void lblUtilValidarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilValidarMousePressed
        tableusers.setRowCount(0);

        ArrayList<User> users = utilizadorController.searchUser((String) jcbUserSearch.getSelectedItem(), txtUserSearch.getText());
        if (users.isEmpty()) {
            JOptionPane.showMessageDialog(this, "0 resultados encontrados para a pesquisada efetuada.", "Resultados", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i = 0; i < users.size(); i++) {
                tableusers.addRow(new Object[]{users.get(i).getNome(), users.get(i).getDatacriacao()});
            }
        }
        tableusers.fireTableDataChanged();
    }//GEN-LAST:event_lblUtilValidarMousePressed

    private void lblDefinicoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDefinicoesMousePressed
        new AssociationSettings().setVisible(true);
    }//GEN-LAST:event_lblDefinicoesMousePressed

    private void lblSocBtnApagarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnApagarMousePressed
        try {
            Object socio = tblSocios.getValueAt(tblSocios.getSelectedRow(), 0);
            String numero = socio.toString();
            int selectedOption = JOptionPane.showOptionDialog(this,
                    "Deseja mesmo remover o sócio seleccionado?",
                    "Remover sócio",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    joptionpaneoptions,
                    joptionpaneoptions[1]);
            if (selectedOption == JOptionPane.YES_OPTION) {
                boolean retorno = socioController.apagarSocio(numero);
                if (retorno == true) {
                    JOptionPane.showMessageDialog(this, "Sócio com o numero " + numero + " removido com sucesso.", "Remover sócio", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Remoção impossível.", "Remover sócio", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Nenhum sócio seleccionado para remoção. \nEfetue uma pesquisa primeiro.", "Impossivel apagar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lblSocBtnApagarMousePressed

    private void lblSocBtnCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnCategoriaMousePressed
        new Category().setVisible(true);
    }//GEN-LAST:event_lblSocBtnCategoriaMousePressed

    private void lblSocBtnRenumerarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocBtnRenumerarMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Desenha mesmo prosseguir com a renumeração dos sócios ativos?\n Esta ação é IRREVERSÍVEL!",
                "Renumerar sócios",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            boolean retorno = socioController.renumerarSocios();
            if (retorno == true) {
                JOptionPane.showMessageDialog(this, "Os sócios ativos foram renumerados com sucesso.", "Renumerar sócios", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Renumeração impossível de momento.", "Renumerar sócios", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_lblSocBtnRenumerarMousePressed

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(196, 219, 255));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }

    private void setAssociationName() {
        try {
            Association nomeAssociacao = assocController.obterAssociacao();
            lblNomeAssociacao.setText(nomeAssociacao.getNome());
        } catch (NullPointerException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(new String("")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnRadioQuotasInativos;
    private javax.swing.JRadioButton btnRadioSocInativos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbQuotasPesquisar;
    private javax.swing.JComboBox<String> jcbSocPesquisar;
    private javax.swing.JComboBox<String> jcbUserSearch;
    private javax.swing.JPanel jplBase;
    private javax.swing.JPanel jplCardBase;
    private javax.swing.JPanel jplCardEstatisticas;
    private javax.swing.JPanel jplCardHome;
    private javax.swing.JPanel jplCardListagens;
    private javax.swing.JPanel jplCardQuotas;
    private javax.swing.JPanel jplCardSocios;
    private javax.swing.JPanel jplCardUtilizadores;
    private javax.swing.JPanel jplClose;
    private javax.swing.JPanel jplListaUtilizadores;
    private javax.swing.JPanel jplListagens;
    private javax.swing.JPanel jplMinimize;
    private javax.swing.JPanel jplModalidades;
    private javax.swing.JPanel jplQuotas;
    private javax.swing.JPanel jplQuotasBarraFerramentas;
    private javax.swing.JPanel jplSideBar;
    private javax.swing.JPanel jplSocBarraFerramentas;
    private javax.swing.JPanel jplSocQuotasTabela;
    private javax.swing.JPanel jplSocTabela;
    private javax.swing.JPanel jplSocios;
    private javax.swing.JPanel jplTop;
    private javax.swing.JPanel jplUtilBarraFerramentas;
    private javax.swing.JPanel jplUtilizadores;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAjuda;
    private javax.swing.JLabel lblBotaoListagens;
    private javax.swing.JLabel lblBotaoModalidades;
    private javax.swing.JLabel lblBotaoQuotas;
    private javax.swing.JLabel lblBotaoSocios;
    private javax.swing.JLabel lblBotaoUtilizadores;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblCalculator;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDefinicoes;
    private javax.swing.JLabel lblEstatisticasTitulo;
    private javax.swing.JLabel lblHomeSociosativos;
    private javax.swing.JLabel lblListagensDescricao;
    private javax.swing.JLabel lblListagensTitulo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblModalidadesDescricao;
    private javax.swing.JLabel lblNomeAssociacao;
    private javax.swing.JLabel lblQuoBtnConsultar;
    private javax.swing.JLabel lblQuoBtnImprimir;
    private javax.swing.JLabel lblQuoBtnPagarQuotas;
    private javax.swing.JLabel lblQuoConsultar;
    private javax.swing.JLabel lblQuoImprimir;
    private javax.swing.JLabel lblQuoPagar;
    private javax.swing.JLabel lblQuotasDescricao;
    private javax.swing.JLabel lblQuotasPesquisar;
    private javax.swing.JLabel lblQuotasTitulo;
    private javax.swing.JLabel lblQuotasValidar;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblSocBtnAlterarSocio;
    private javax.swing.JLabel lblSocBtnApagar;
    private javax.swing.JLabel lblSocBtnCartao;
    private javax.swing.JLabel lblSocBtnCategoria;
    private javax.swing.JLabel lblSocBtnCriarSocio;
    private javax.swing.JLabel lblSocBtnDesativar;
    private javax.swing.JLabel lblSocBtnRenumerar;
    private javax.swing.JLabel lblSocCartao1;
    private javax.swing.JLabel lblSocEditar;
    private javax.swing.JLabel lblSocInativar;
    private javax.swing.JLabel lblSocNovo;
    private javax.swing.JLabel lblSocPesquisar;
    private javax.swing.JLabel lblSocRemover1;
    private javax.swing.JLabel lblSocRenumerar;
    private javax.swing.JLabel lblSocTitulo;
    private javax.swing.JLabel lblSocValidar;
    private javax.swing.JLabel lblSociosDescricao;
    private javax.swing.JLabel lblSociosTitulo;
    private javax.swing.JLabel lblUtilBtnAlterarUtil;
    private javax.swing.JLabel lblUtilBtnCriarUtil;
    private javax.swing.JLabel lblUtilBtnRemoverUtil;
    private javax.swing.JLabel lblUtilEditar;
    private javax.swing.JLabel lblUtilNovo;
    private javax.swing.JLabel lblUtilPesquisar;
    private javax.swing.JLabel lblUtilRemover;
    private javax.swing.JLabel lblUtilTitulo;
    private javax.swing.JLabel lblUtilValidar;
    private javax.swing.JLabel lblUtilizadoresDescricao;
    private javax.swing.JLabel lblola;
    private javax.swing.JLabel lblusername;
    private javax.swing.JScrollPane scrollQuotas;
    private javax.swing.JScrollPane scrollSocios;
    private javax.swing.JScrollPane scrollUsers;
    private javax.swing.JTable tblQuotas;
    private javax.swing.JTable tblSocios;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtHomeTotalSocios;
    private javax.swing.JTextField txtQuotasPesquisar;
    private javax.swing.JTextField txtSocPesquisar;
    private javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
}
