/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import myassociation.controller.AssociationController;
import myassociation.controller.MemberController;
import myassociation.controller.SportController;
import myassociation.controller.UserController;
import myassociation.model.Member;

/**
 *
 * @author Cláudio Felgueiras
 */
public class SubscribeSport extends javax.swing.JFrame {

    private static final long serialVersionUID = 9159801668819494747L;

    private AssociationController associacaoController;
    private SportController modalidadeController;
    private UserController utilizadorController;
    private MemberController socioController;
    private javax.swing.table.DefaultTableModel tabelasocios = new javax.swing.table.DefaultTableModel(new String[]{"Numero", "NIF", "Nome", "Telefone", "Telemovel", "Morada", "Email", "Data criação", "Data modificação", "Utilizador", "Categoria"}, 0);
    String username;
    private ImageIcon icon;
    private final Object[] joptionpaneoptions = {"Sim", "Não"};

    /**
     * Creates new form CriarUtilizador
     *
     * @param username
     */
    public SubscribeSport(String username) {
        initComponents();
        modalidadeController = new SportController();
        associacaoController = new AssociationController();
        utilizadorController = new UserController();
        socioController = new MemberController();
        tblSocios.setModel(tabelasocios);
        tblSocios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jcbModalidades.setModel(new DefaultComboBoxModel<>(modalidadeController.listaModalidades()));
        this.username = username;
        this.setLocationRelativeTo(null);
        this.setIconImage(associacaoController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplUtilCriar = new javax.swing.JPanel();
        btnModCriar = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblModCriar = new javax.swing.JLabel();
        lblInscreverModalidade = new javax.swing.JLabel();
        jcbSocPesquisar = new javax.swing.JComboBox<>();
        txtSocPesquisar = new javax.swing.JTextField();
        btnRadioSocInativos = new javax.swing.JRadioButton();
        lblSocValidar = new javax.swing.JLabel();
        scrollSocios = new javax.swing.JScrollPane();
        tblSocios = new javax.swing.JTable();
        jcbModalidades = new javax.swing.JComboBox<>();
        lblSocPesquisar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmCreateUser"); // NOI18N
        setUndecorated(true);

        jplUtilCriar.setBackground(new java.awt.Color(246, 246, 246));
        jplUtilCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplUtilCriar.setFocusable(false);
        jplUtilCriar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModCriar.setBackground(new java.awt.Color(255, 255, 255));
        btnModCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModCriar.setForeground(new java.awt.Color(0, 98, 206));
        btnModCriar.setText("Inscrever");
        btnModCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCriarActionPerformed(evt);
            }
        });
        jplUtilCriar.add(btnModCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 93, 40));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 32, 32));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 32, 32));

        lblModCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModCriar.setForeground(new java.awt.Color(0, 98, 206));
        lblModCriar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModCriar.setText("INSCREVER MODALIDADE");
        jplUtilCriar.add(lblModCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 290, 30));

        lblInscreverModalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInscreverModalidade.setText("Modalidade:");
        jplUtilCriar.add(lblInscreverModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 90, 37));

        jcbSocPesquisar.setBackground(new java.awt.Color(240, 240, 240));
        jcbSocPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbSocPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Numero", "NIF", "Telefone", "Telemovel", "Morada", "Email" }));
        jcbSocPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplUtilCriar.add(jcbSocPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 149, 37));
        jplUtilCriar.add(txtSocPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 490, 38));

        btnRadioSocInativos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRadioSocInativos.setText("Inativos");
        btnRadioSocInativos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplUtilCriar.add(btnRadioSocInativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 53, 97, 30));

        lblSocValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main_images/Filtrar_40px.png"))); // NOI18N
        lblSocValidar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSocValidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSocValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSocValidarMousePressed(evt);
            }
        });
        jplUtilCriar.add(lblSocValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, 38));

        tblSocios.setBackground(new java.awt.Color(246, 246, 246));
        tblSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        scrollSocios.setViewportView(tblSocios);

        jplUtilCriar.add(scrollSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 930, 340));

        jplUtilCriar.add(jcbModalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 340, 37));

        lblSocPesquisar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSocPesquisar1.setText("Pesquisar:");
        jplUtilCriar.add(lblSocPesquisar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplUtilCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int selectedOption = JOptionPane.showOptionDialog(this,
                "Deseja mesmo sair?",
                "Criar Modalidade",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                joptionpaneoptions,
                joptionpaneoptions[1]);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void btnModCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCriarActionPerformed


//boolean socioinscrito = modalidadeController.inscreverModalidade(tabelasocios.getValueAt(WIDTH, WIDTH), (String)jcbModalidades.getSelectedItem(), username);

//        if (txtModNome.getText().isEmpty() || txtModResponsavel.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Os dados da modalidade não podem ser vazios. \nInsira um nome e um responsável.", "Criar Modalidade", JOptionPane.ERROR_MESSAGE);
//        } else {
//            boolean modcriada = modalidadeController.criarModalidade(txtModNome.getText(), txtModResponsavel.getText(), true, username);
//            if (modcriada) {
//                JOptionPane.showMessageDialog(null, "Modalidade criada com sucesso.", "Modalidade", JOptionPane.INFORMATION_MESSAGE);
//                txtModNome.setText("");
//                txtModResponsavel.setText("");
//            } else {
//                JOptionPane.showMessageDialog(null, "Modalidade já existe.\n Insira outro nome de modalidade.", "Modalidade", JOptionPane.ERROR_MESSAGE);
//                txtModNome.setText("");
//                txtModResponsavel.setText("");
//            }
//        }
    }//GEN-LAST:event_btnModCriarActionPerformed

    private void lblSocValidarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSocValidarMousePressed
        tabelasocios.setRowCount(0);

        ArrayList<Member> socioPesquisado = socioController.pesquisarSocio((String) jcbSocPesquisar.getSelectedItem(), txtSocPesquisar.getText(), !btnRadioSocInativos.isSelected());
        if (socioPesquisado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "0 resultados encontrados para a pesquisada efetuada.", "Resultados", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i = 0; i < socioPesquisado.size(); i++) {
                tabelasocios.addRow(new Object[]{socioPesquisado.get(i).getNumero(), socioPesquisado.get(i).getNif(), socioPesquisado.get(i).getNome(), socioPesquisado.get(i).getTelefone(), socioPesquisado.get(i).getTelemovel(), socioPesquisado.get(i).getMorada(), socioPesquisado.get(i).getEmail(), socioPesquisado.get(i).getDatacriacao(), socioPesquisado.get(i).getDatamodif(), socioPesquisado.get(i).getUtilizador(), socioPesquisado.get(i).getCategoria()});
            }
        }
        tabelasocios.fireTableDataChanged();
    }//GEN-LAST:event_lblSocValidarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModCriar;
    private javax.swing.JRadioButton btnRadioSocInativos;
    private javax.swing.JComboBox<String> jcbModalidades;
    private javax.swing.JComboBox<String> jcbSocPesquisar;
    private javax.swing.JPanel jplUtilCriar;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblInscreverModalidade;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblModCriar;
    private javax.swing.JLabel lblSocPesquisar1;
    private javax.swing.JLabel lblSocValidar;
    private javax.swing.JScrollPane scrollSocios;
    private javax.swing.JTable tblSocios;
    private javax.swing.JTextField txtSocPesquisar;
    // End of variables declaration//GEN-END:variables
}
