/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myassociation.ui;

import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myassociation.controller.AssociationController;
import myassociation.controller.MemberController;
import myassociation.model.Member;
import myassociation.reports.ImprimeCartaoAssociado;

/**
 *
 * @author Cláudio Felgueiras
 */
public class ViewMember extends javax.swing.JFrame {

    private static final long serialVersionUID = 112749752048228437L;

    private MemberController socioController = new MemberController();
    private ImprimeCartaoAssociado imprimircartao = new ImprimeCartaoAssociado();
    private AssociationController assocController = new AssociationController();
    private Point initialClick;
    private BufferedImage foto = null;
    private File ficheiro;
    private Member member;

    /**
     * Creates new form CriarSocio
     *
     * @param member
     */
    public ViewMember(Member member) throws IOException {
        initComponents();
        this.setIconImage(assocController.applicationIcon());
        this.member = member;
        setDados();
        this.setLocationRelativeTo(null);
        this.setIconImage(assocController.applicationIcon());
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplEditarSocio = new javax.swing.JPanel();
        checkSociosEstado = new javax.swing.JCheckBox();
        lblSociosEstado = new javax.swing.JLabel();
        lblSociosEmail = new javax.swing.JLabel();
        txtSociosEmail = new javax.swing.JTextField();
        lblSociosMorada = new javax.swing.JLabel();
        txtSociosMorada = new javax.swing.JTextField();
        lblSociosFoto = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        txtSociosTelemovel = new javax.swing.JTextField();
        lblSociosTelemovel = new javax.swing.JLabel();
        lblSociosTelefone = new javax.swing.JLabel();
        txtSociosTelefone = new javax.swing.JTextField();
        txtSociosNome = new javax.swing.JTextField();
        lblSociosNome = new javax.swing.JLabel();
        txtSociosNIF = new javax.swing.JTextField();
        lblSociosNIF = new javax.swing.JLabel();
        lblSociosNumero = new javax.swing.JLabel();
        txtSociosNumero = new javax.swing.JTextField();
        btnSociosCancelar = new javax.swing.JButton();
        btnSociosImprimir = new javax.swing.JButton();
        lblVisualizarSocioTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmViewMember"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jplEditarSocio.setBackground(new java.awt.Color(246, 246, 246));
        jplEditarSocio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 98, 206), 2));
        jplEditarSocio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jplEditarSocioMouseDragged(evt);
            }
        });
        jplEditarSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jplEditarSocioMousePressed(evt);
            }
        });
        jplEditarSocio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkSociosEstado.setBackground(new java.awt.Color(255, 255, 255));
        checkSociosEstado.setEnabled(false);
        jplEditarSocio.add(checkSociosEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        lblSociosEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosEstado.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosEstado.setText("Ativo:");
        jplEditarSocio.add(lblSociosEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 66, 25));

        lblSociosEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosEmail.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosEmail.setText("E-mail:");
        jplEditarSocio.add(lblSociosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 66, 26));

        txtSociosEmail.setEnabled(false);
        jplEditarSocio.add(txtSociosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 460, 26));

        lblSociosMorada.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosMorada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosMorada.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosMorada.setText("Morada:");
        jplEditarSocio.add(lblSociosMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 66, 26));

        txtSociosMorada.setEnabled(false);
        jplEditarSocio.add(txtSociosMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 460, 26));

        lblSociosFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSociosFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplEditarSocio.add(lblSociosFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 118, 113));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(0, 98, 206));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jplEditarSocio.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 32, 32));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 98, 206));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jplEditarSocio.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 32, 32));

        txtSociosTelemovel.setEnabled(false);
        jplEditarSocio.add(txtSociosTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, 25));

        lblSociosTelemovel.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosTelemovel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosTelemovel.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTelemovel.setText("Telemovel:");
        jplEditarSocio.add(lblSociosTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 66, 26));

        lblSociosTelefone.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosTelefone.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosTelefone.setText("Telefone:");
        jplEditarSocio.add(lblSociosTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 58, 22));

        txtSociosTelefone.setEnabled(false);
        jplEditarSocio.add(txtSociosTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 25));

        txtSociosNome.setEnabled(false);
        jplEditarSocio.add(txtSociosNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 321, 26));

        lblSociosNome.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNome.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNome.setText("Nome:");
        jplEditarSocio.add(lblSociosNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 62, 26));

        txtSociosNIF.setEnabled(false);
        jplEditarSocio.add(txtSociosNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 210, 26));

        lblSociosNIF.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNIF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNIF.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNIF.setText("NIF:");
        jplEditarSocio.add(lblSociosNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 62, 26));

        lblSociosNumero.setBackground(new java.awt.Color(255, 255, 255));
        lblSociosNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSociosNumero.setForeground(new java.awt.Color(0, 98, 206));
        lblSociosNumero.setText("Número:");
        jplEditarSocio.add(lblSociosNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 62, 26));

        txtSociosNumero.setEnabled(false);
        jplEditarSocio.add(txtSociosNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 208, 26));

        btnSociosCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSociosCancelar.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosCancelar.setText("Cancelar");
        btnSociosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosCancelarActionPerformed(evt);
            }
        });
        jplEditarSocio.add(btnSociosCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 93, 40));

        btnSociosImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSociosImprimir.setForeground(new java.awt.Color(0, 98, 206));
        btnSociosImprimir.setText("Imprimir");
        btnSociosImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosImprimirActionPerformed(evt);
            }
        });
        jplEditarSocio.add(btnSociosImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 93, 40));

        lblVisualizarSocioTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblVisualizarSocioTitulo.setForeground(new java.awt.Color(0, 98, 206));
        lblVisualizarSocioTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisualizarSocioTitulo.setText("VISUALIZAR SÓCIO");
        jplEditarSocio.add(lblVisualizarSocioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 430, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplEditarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplEditarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSociosImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosImprimirActionPerformed
        File savePath = null;
        JFileChooser chooser = new JFileChooser();
        int retrival = chooser.showSaveDialog(null);

        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                savePath = chooser.getSelectedFile();
                boolean result = false;
                if (savePath.toString().endsWith(".pdf")) {
                    result = imprimircartao.imprimirCartaoAssociado(member, savePath.toString());
                } else {
                    result = imprimircartao.imprimirCartaoAssociado(member, savePath.toString() + ".pdf");
                }
                if (result = false) {
                    JOptionPane.showMessageDialog(null, "Falha ao imprimir cartão de sócio.", "Impressão de cartão", JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                }
            } catch (Exception ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Falha ao imprimir cartão de sócio.", "Impressão de cartão", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnSociosImprimirActionPerformed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        this.dispose();
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void btnSociosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSociosCancelarActionPerformed

    private void jplEditarSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEditarSocioMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_jplEditarSocioMousePressed

    private void jplEditarSocioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplEditarSocioMouseDragged
        int thisX = this.getLocation().x;
        int thisY = this.getLocation().y;

        // Determine how much the mouse moved since the initial click
        int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
        int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        this.setLocation(X, Y);
    }//GEN-LAST:event_jplEditarSocioMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSociosCancelar;
    private javax.swing.JButton btnSociosImprimir;
    private javax.swing.JCheckBox checkSociosEstado;
    private javax.swing.JPanel jplEditarSocio;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSociosEmail;
    private javax.swing.JLabel lblSociosEstado;
    private javax.swing.JLabel lblSociosFoto;
    private javax.swing.JLabel lblSociosMorada;
    private javax.swing.JLabel lblSociosNIF;
    private javax.swing.JLabel lblSociosNome;
    private javax.swing.JLabel lblSociosNumero;
    private javax.swing.JLabel lblSociosTelefone;
    private javax.swing.JLabel lblSociosTelemovel;
    private javax.swing.JLabel lblVisualizarSocioTitulo;
    private javax.swing.JTextField txtSociosEmail;
    private javax.swing.JTextField txtSociosMorada;
    private javax.swing.JTextField txtSociosNIF;
    private javax.swing.JTextField txtSociosNome;
    private javax.swing.JTextField txtSociosNumero;
    private javax.swing.JTextField txtSociosTelefone;
    private javax.swing.JTextField txtSociosTelemovel;
    // End of variables declaration//GEN-END:variables

    private byte[] convertImagetoByte(BufferedImage foto) throws IOException {
        byte[] fotoinbytes;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        if (foto == null) {
            fotoinbytes = new byte[0];
        } else {
            try {
                foto = ImageIO.read(ficheiro);

                ImageIO.write(foto, "jpg", baos);
                baos.flush();
                baos.toByteArray();
            } catch (IOException ex) {
                Logger.getLogger(ViewMember.class.getName()).log(Level.SEVERE, null, ex);
            }
            fotoinbytes = baos.toByteArray();;
        }
        return fotoinbytes;
    }

    private Icon convertBytetoIcon(byte[] fotografia) {
        ImageIcon icone = null;
        try {
            byte[] byteArray = fotografia;
            BufferedImage foto = null;
            ImageIcon imageIcon = new ImageIcon(byteArray);
            BufferedImage theImage = ImageIO.read(new ByteArrayInputStream(byteArray));
            Image fotodim = theImage.getScaledInstance(lblSociosFoto.getWidth(), lblSociosFoto.getHeight(), Image.SCALE_SMOOTH);
            icone = new ImageIcon(fotodim);

        } catch (IOException ex) {
            System.out.println(ex);
        } catch (NullPointerException exep) {
            System.out.println(exep);
        }
        return icone;
    }

    private void setDados() {
        txtSociosNumero.setText(member.getNumero());
        txtSociosNome.setText(member.getNome());
        txtSociosMorada.setText(member.getMorada());
        txtSociosNIF.setText(member.getNif());
        txtSociosEmail.setText(member.getEmail());
        txtSociosTelefone.setText(member.getTelefone());
        txtSociosTelemovel.setText(member.getTelemovel());
        lblSociosFoto.setIcon(convertBytetoIcon(member.getFotografia()));
        checkSociosEstado.setSelected(member.getEstado());
    }
}
